Repository hikari-py/hikari, pull requests merged in 2020-10, with the labels that each got.

#255 Fix documentation references
  hikari/__init__.py
  hikari/api/chunker.py
  hikari/api/entity_factory.py
  hikari/api/event_dispatcher.py
  hikari/api/event_factory.py
  hikari/api/rest.py
  hikari/config.py
  hikari/impl/buckets.py
  hikari/impl/shard.py
  hikari/internal/cache.py
Labels: documentation

#259 Fix AttributeError on create_role
  hikari/impl/rest.py
Labels: bug

#260 Rename `USE_VAD` to `USE_VOICE_ACTIVITY` to reduce confusion
  hikari/permissions.py
Labels: enhancement

#250 Task/deprecating duplicated stub helpers
  hikari/channels.py
  tests/hikari/events/test_channel_events.py
  tests/hikari/events/test_shard_events.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/impl/test_stateful_guild_chunker.py
  tests/hikari/test_applications.py
  tests/hikari/test_channels.py
  tests/hikari/test_event_stream.py
  tests/hikari/test_guilds.py
  tests/hikari/test_messages.py
  tests/hikari/test_users.py
Labels: medium, testing

#268 Fix shutting down default executor several times
  hikari/impl/bot.py
Labels: bug

#249 New tests
  hikari/errors.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
  tests/hikari/internal/test_collections.py
  tests/hikari/test_channels.py
Labels: enhancement, testing

#265 Task/intflag
  docs/documentation.mako
  hikari/channels.py
  hikari/errors.py
  hikari/guilds.py
  hikari/impl/bot.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/intents.py
  hikari/internal/cache.py
  hikari/internal/enums.py
  hikari/internal/enums.pyi
  hikari/internal/flag.py
  hikari/messages.py
  hikari/permissions.py
  hikari/presences.py
  hikari/users.py
  scripts/enum_benchmark.py
  scripts/flag_benchmark.py
  tests/hikari/internal/test_enums.py
  tests/hikari/internal/test_flag.py
  tests/hikari/test_channels.py
  tests/hikari/test_errors.py
  tests/hikari/test_permissions.py
Labels: enhancement, optimization

#272 Added batch files to execute examples from cmd
  examples/hello_world/hello_world.bat
  examples/image_resources/image_resources.bat
Labels: enhancement

#274 Remove duplicate `__str__` code on enums
  hikari/applications.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/errors.py
  hikari/guilds.py
  hikari/invites.py
  hikari/messages.py
  hikari/presences.py
  hikari/users.py
  hikari/webhooks.py
Labels: enhancement

#276 General tidyups
  hikari/__init__.py
  hikari/snowflakes.py
  pages/index.html
Labels: enhancement

#279 Moved CI container scripts to master [rebuild containers]
  .travis.yml
  pipelines/docker/stackless-3.8.0b3/Dockerfile
Labels: devops

#282 Added CPython 3.10.0-a1 to CI.
  .travis.yml
Labels: blocked, devops

#281 Changed max version in setup.py and added Python 3.10 TROVE classifier.
  setup.py
Labels: blocked, dependencies

#278 And more testing
  hikari/internal/aio.py
  hikari/internal/time.py
  pipelines/pytest.nox.py
  tests/hikari/events/test_message_events.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/internal/test_collections.py
  tests/hikari/internal/test_ux.py
  tests/hikari/test_colors.py
  tests/hikari/test_errors.py
  tests/hikari/test_event_stream.py
  tests/hikari/test_users.py
Labels: enhancement, testing

#285 Fix documentation and tests
  hikari/api/rest.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_rest.py
Labels: enhancement, testing

#275 Implemented default max-retry of 60s.
  .isort.cfg
  hikari/api/rest.py
  hikari/errors.py
  hikari/impl/bot.py
  hikari/impl/buckets.py
  hikari/impl/rest.py
  pipelines/nox.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_rest.py
Labels: bug, enhancement, optimization

#286 Redefined UNDEFINED to only use enum facade if type-checking.
  docs/documentation.mako
  hikari/undefined.py
  tests/hikari/test_undefined.py
Labels: documentation, enhancement, optimization

#280 Moved default Travis CI build stages to use CPython 3.9.0.
  .travis.yml
  README.md
  scripts/test-job.sh
  setup.py
Labels: blocked, devops

#298 Fix uploading code coverage to codeclimate
  .travis.yml
Labels: devops

#302 Fix travis CI and deploy script [rebuild containers]
  .github/dependabot.yml
  .travis.yml
  README.md
  hikari/_about.py
  scripts/deploy-manually.sh
  scripts/deploy-pages.sh
Labels: devops

#309 Fix travis CI issues
  .travis.yml
  scripts/test-job.sh
Labels: devops

#295 Bump mypy from 0.782 to 0.790
  dev-requirements.txt
  hikari/impl/rest.py
Labels: dependencies

#294 Update docstring of `collections.copy_mapping`
  hikari/internal/collections.py
Labels: documentation

#292 Fix not documenting UNDEFINED properly
  hikari/undefined.py
  hikari/undefined.pyi
Labels: documentation

#312 Fix max_rate_limit
  hikari/errors.py
  hikari/impl/buckets.py
Labels: bug

#311 Dont document index.html in the index
  docs/patched_pdoc.py
Labels: bug

#314 New tests
  hikari/__init__.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
  tests/hikari/internal/test_collections.py
  tests/hikari/test_errors.py
  tests/hikari/test_undefined.py
Labels: enhancement, testing

#315 New JSON Codes and remove `PUBLIC` and `PUBLIC_DISABLED` flags
  hikari/errors.py
  hikari/guilds.py
Labels: enhancement

#316 Bot and webhook integrations
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/webhooks.py
  pages/index.html
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
Labels: bug, enhancement

#334 Add missing copyright
  pipelines/format.nox.py
  scripts/deploy-manually.sh
  scripts/deploy-pages.sh
  scripts/deploy.sh
  scripts/deploy_webhook.py
  scripts/test-job.sh
Labels: enhancement

#335 Dont suppress errors raised by run_once
  hikari/impl/bot.py
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: bug, enhancement
