Repository hikari-py/hikari, pull requests merged in 2020-08, with the labels that each got.

#10 Updated deploy script to re-generate mypy stubs for --strict support.
  scripts/deploy.sh
  scripts/deploy_webhook.py
Labels: bug

#4 Github switch
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  docs/config.mako
  docs/head.mako
  docs/html.mako
  hikari/_about.py
  pages/index.html
  pipelines/config.py
  pipelines/format.nox.py
Labels: documentation

#6 Implement "chunk" method for lazy iterator and add __iter__ override for more helpful error message.
  hikari/utilities/iterators.py
Labels: documentation, enhancement

#12 Amended 'BotApp.run' to not reraise exceptions caused by graceful shutdown.
  hikari/impl/bot.py
Labels: bug

#15 Added tests for Users
  .github/ISSUE_TEMPLATE/feature_request.md
  hikari/__init__.py
  hikari/models/webhooks.py
  hikari/traits.py
  tests/hikari/models/test_users.py
Labels: enhancement

#17 Re-encrypted travis deployment credential.
  .travis.yml
Labels: bug

#13 Several cache optimisations and fixes
  .run/Unit Tests.run.xml
  hikari/impl/stateful_cache.py
  tests/hikari/impl/test_stateful_cache.py
Labels: bug, enhancement

#23 Update users.py
  hikari/models/users.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/models/test_users.py
Labels: documentation

#25 Added init pipeline
  README.md
  flake8-requirements.txt
  pipelines/development.nox.py
  pipelines/flake8.nox.py
Labels: enhancement

#28 Added an automerge configuration.
  .github/auto-merge.yml
Labels: automerge

#29 Enable automatic dependency updates
  .github/dependabot.yml
Labels: automerge

#27 Added CLICOLOR and CLICOLOR_FORCE environment variable support.
  hikari/utilities/art.py
Labels: automerge, enhancement

#51 Adjusted error handling of events a little.
  hikari/impl/event_manager_base.py
  insomnia/README.md
  insomnia/v7.yaml
Labels: bug, enhancement

#53 Added missing import to `__init__.py`
  hikari/__init__.py
  hikari/impl/bot.py
  hikari/traits.py
Labels: bug

#79 Added IDEA file templates with built-in license headers.
  .idea/fileTemplates/Cascading Style Sheet.css
  .idea/fileTemplates/JS Script.js
  .idea/fileTemplates/JSON File.json
  .idea/fileTemplates/Mako Template.mako
  .idea/fileTemplates/Nox Pipeline.py
  .idea/fileTemplates/Python Module.py
  .idea/fileTemplates/YAML File.yml
  .idea/fileTemplates/py.test Test Suite.py
  pipelines/format.nox.py
Labels: tidyups and resources

#82 Bugfix/77 wait for race
  hikari/api/event_dispatcher.py
  hikari/cli.py
  hikari/events/base_events.py
  hikari/impl/bot.py
  hikari/impl/event_manager_base.py
  hikari/impl/shard.py
  hikari/utilities/aio.py
  tests/hikari/events/test_base_events.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_shard.py
Labels: bug

#85 Fixing stackless container to die properly.
  .travis.yml
Labels: bug

#87 Reimplemented BotApp.run to have more concrete signal handling and to tidy up resources.
  hikari/impl/bot.py
Labels: enhancement, optimization

#89 Bugfixes for race conditions in starting multisharded bots, and debug…
  hikari/impl/bot.py
  hikari/utilities/aio.py
Labels: bug, enhancement

#84 Draft: Feature/event methods
  hikari/api/cache.py
  hikari/events/channel_events.py
  hikari/events/guild_events.py
  hikari/events/member_events.py
  hikari/events/message_events.py
  tests/hikari/events/test_channel_events.py
  tests/hikari/hikari_test_helpers.py
Labels: documentation, enhancement, good first issue, help wanted

#95 Upgraded and baselined to black v20.8b1, which causes several major reformats.
  hikari/api/cache.py
  hikari/api/entity_factory.py
  hikari/api/event_dispatcher.py
  hikari/api/event_factory.py
  hikari/api/rest.py
  hikari/applications.py
  hikari/channels.py
  hikari/embeds.py
  hikari/files.py
  hikari/guilds.py
  hikari/impl/bot.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/special_endpoints.py
  hikari/impl/stateful_cache.py
  hikari/impl/stateful_event_manager.py
  hikari/impl/voice.py
  hikari/invites.py
  hikari/iterators.py
  hikari/users.py
  hikari/utilities/cache.py
  hikari/utilities/data_binding.py
  hikari/utilities/routes.py
  hikari/utilities/version_sniffer.py
  hikari/webhooks.py
  pipelines/flake8.nox.py
  pipelines/format.nox.py
  pipelines/mypy.nox.py
  tests/hikari/events/test_base_events.py
  tests/hikari/events/test_message_events.py
  tests/hikari/events/test_typing_events.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rate_limits.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_stateful_cache.py
  tests/hikari/test_audit_logs.py
  tests/hikari/test_guilds.py
  tests/hikari/test_sessions.py
  tests/hikari/test_users.py
  tests/hikari/utilities/test_attr_extensions.py
  tests/hikari/utilities/test_flag.py
  tests/hikari/utilities/test_routes.py
  tests/hikari/utilities/test_version_sniffer.py
Labels: automation, tidyups and resources

#90 Handling aiohttp.WSServerUpgradeError
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: bug, enhancement

#92 Add deprecation warning to use of intents.
  hikari/impl/bot.py
Labels: documentation, enhancement

#93 Gateway websocket closure forcing, and new missing test cases.
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: enhancement, testing

#91 Defaulted state to being enabled by default on BotApp.
  hikari/impl/bot.py
Labels: enhancement

#96 Bumped to pdoc 0.9.0.
  .travis.yml
  dev-requirements.txt
  hikari/traits.py
  mypy-requirements.txt
  pipelines/format.nox.py
  pipelines/mypy.nox.py
  pipelines/nox.py
  pipelines/pdoc3.nox.py
  pipelines/safety.nox.py
  scripts/deploy-pages.sh
Labels: automation, bug, documentation

#97 Optimisations to datetime parsing.
  hikari/impl/event_manager_base.py
  hikari/utilities/date.py
  hikari/utilities/reflect.py
  requirements.txt
  tests/hikari/impl/test_event_manager_base.py
Labels: optimization

#103 Fix naming issue in shard ratelimiter
  hikari/impl/shard.py
Labels: enhancement

#102 Bugfix/closures
  hikari/impl/bot.py
  hikari/impl/buckets.py
  hikari/impl/rate_limits.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  scripts/gateway_stub.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_rate_limits.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
Labels: bug, enhancement, help wanted
