Repository hikari-py/hikari, pull requests merged in 2020-09, with the labels that each got.

#110 Freeze requirements and add update flag to pipelines
  dev-requirements.txt
  flake8-requirements.txt
  pipelines/development.nox.py
  pipelines/format.nox.py
  pipelines/pytest.nox.py
  pipelines/safety.nox.py
  pipelines/twemoji.nox.py
  requirements.txt
Labels: dependencies, enhancement

#109 Enabled flake8 to run on tests
  .flake8
  hikari/utilities/routes.py
  pipelines/config.py
  pipelines/flake8.nox.py
  tests/hikari/events/test_base_events.py
  tests/hikari/events/test_channel_events.py
  tests/hikari/events/test_guild_events.py
  tests/hikari/events/test_member_events.py
  tests/hikari/events/test_message_events.py
  tests/hikari/events/test_reaction_events.py
  tests/hikari/events/test_role_events.py
  tests/hikari/events/test_typing_events.py
  tests/hikari/events/test_voice_events.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_rate_limits.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_stateful_cache.py
  tests/hikari/impl/test_stateless_cache.py
  tests/hikari/impl/test_stateless_event_manager.py
  tests/hikari/impl/test_stateless_guild_chunker.py
  tests/hikari/test_applications.py
  tests/hikari/test_audit_logs.py
  tests/hikari/test_channels.py
  tests/hikari/test_config.py
  tests/hikari/test_errors.py
  tests/hikari/test_guilds.py
  tests/hikari/test_invites.py
  tests/hikari/test_messages.py
  tests/hikari/test_presences.py
  tests/hikari/test_snowflake.py
  tests/hikari/test_users.py
  tests/hikari/test_webhooks.py
  tests/hikari/utilities/test_data_binding.py
  tests/hikari/utilities/test_date.py
  tests/hikari/utilities/test_reflect.py
  tests/hikari/utilities/test_routes.py
  tests/hikari/utilities/test_version_sniffer.py
Labels: enhancement, testing

#112 Remove "fqn" helper methods plus some generalisation
  tests/hikari/hikari_test_helpers.py
Labels: enhancement, testing

#98 publicly exposed chunk tracking interface
  hikari/api/chunker.py
  hikari/api/event_dispatcher.py
  hikari/api/shard.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/embeds.py
  hikari/errors.py
  hikari/events/shard_events.py
  hikari/files.py
  hikari/guilds.py
  hikari/impl/bot.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/stateful_cache.py
  hikari/impl/stateful_event_manager.py
  hikari/impl/stateful_guild_chunker.py
  hikari/impl/stateless_guild_chunker.py
  hikari/impl/voice.py
  hikari/iterators.py
  hikari/snowflakes.py
  hikari/utilities/cache.py
  hikari/utilities/date.py
  hikari/utilities/event_stream.py
  hikari/utilities/mapping.py
  hikari/utilities/routes.py
  tests/hikari/events/test_channel_events.py
  tests/hikari/events/test_shard_events.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_stateful_cache.py
  tests/hikari/impl/test_stateful_guild_chunker.py
  tests/hikari/impl/test_stateless_guild_chunker.py
  tests/hikari/test_channels.py
  tests/hikari/test_messages.py
  tests/hikari/test_snowflake.py
  tests/hikari/utilities/test_event_stream.py
  tests/hikari/utilities/test_mapping.py
Labels: enhancement

#114 Add REST documentation
  hikari/api/rest.py
Labels: documentation

#115 Documentation consistency fixes
  hikari/api/chunker.py
  hikari/api/event_dispatcher.py
  hikari/api/rest.py
  hikari/channels.py
  hikari/events/shard_events.py
  hikari/files.py
  hikari/impl/bot.py
  hikari/impl/shard.py
  hikari/impl/stateful_guild_chunker.py
  hikari/iterators.py
  hikari/messages.py
  hikari/utilities/cache.py
  hikari/utilities/data_binding.py
  hikari/utilities/event_stream.py
  hikari/webhooks.py
Labels: documentation

#117 Added optional `pip install hikari[speedups]` to get compiled modules.
  .travis.yml
  MANIFEST.in
  README.md
  hikari/utilities/date.py
  pipelines/pytest.nox.py
  requirements.txt
  setup.py
  speedup-requirements.txt
Labels: bug, dependencies, optimization

#118 Added pdoc helper to find reference errors
  docs/documentation.mako
  hikari/impl/buckets.py
Labels: documentation, enhancement

#122 Ensure ExponentialBackOff respects float limitations.
  .travis.yml
  hikari/impl/rate_limits.py
  tests/hikari/impl/test_rate_limits.py
Labels: bug, enhancement

#121 Task/gateway simplification
  README.md
  hikari/api/shard.py
  hikari/banner.txt
  hikari/cli.py
  hikari/config.py
  hikari/errors.py
  hikari/impl/bot.py
  hikari/impl/entity_factory.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/voice.py
  hikari/traits.py
  hikari/utilities/aio.py
  hikari/utilities/art.py
  hikari/utilities/constants.py
  hikari/utilities/ux.py
  hikari/utilities/version_sniffer.py
  pipelines/development.nox.py
  pipelines/flake8.nox.py
  pipelines/pytest.nox.py
  requirements.txt
  tests/hikari/impl/skipped_test_shard.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/test_config.py
  tests/hikari/test_errors.py
  tests/hikari/utilities/test_aio.py
  tests/hikari/utilities/test_version_sniffer.py
Labels: bug, dependencies, documentation, enhancement, help wanted, optimization, testing

#128 Renamed some user flags.
  hikari/users.py
  tests/hikari/impl/test_entity_factory.py
Labels: documentation

#133 Fixed a logic error in websocket init logic
  hikari/impl/shard.py
Labels: bug

#134 avoid the shard ratelimits delaying event dispatch
  hikari/impl/stateful_event_manager.py
  tests/hikari/hikari_test_helpers.py
Labels: bug

#136 Several bug fixes
  hikari/api/rest.py
  hikari/impl/bot.py
  hikari/impl/rest.py
  hikari/impl/shard.py
Labels: bug, enhancement

#140 Fix being unable to shut down bot
  hikari/impl/bot.py
Labels: bug, priority

#137 Added logic to debug flows to remove tokens from output debug logs.
  hikari/impl/rest.py
  hikari/impl/shard.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#141 Add `update_presence` to bot
  hikari/api/entity_factory.py
  hikari/impl/bot.py
  hikari/traits.py
Labels: enhancement

#144 Replace slow `build_entity` and `build_from_entity` methods on cache data class with abstractmethods
  hikari/impl/stateful_cache.py
  hikari/utilities/cache.py
Labels: blocked, optimization, waiting for author

#145 Added shard tests
  .flake8
  hikari/impl/shard.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/skipped_test_shard.py
  tests/hikari/impl/test_shard.py
Labels: enhancement, testing

#146 Dont force to close TCP connectors
  hikari/banner.txt
  hikari/impl/bot.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
Labels: bug

#147 Add newly documented crossposting related endpoints and models.
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/channels.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/utilities/routes.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_channels.py
Labels: enhancement

#149 Task/close revamp
  hikari/errors.py
  hikari/impl/bot.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
Labels: enhancement, optimization

#150 Add methods to BotAware along with moving docs
  hikari/impl/bot.py
  hikari/traits.py
Labels: enhancement

#154 Fixed several bugs in shard/bot run logic.
  hikari/errors.py
  hikari/impl/bot.py
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: bug, enhancement, help wanted

#153 Rename private text channels to DMs
  hikari/api/cache.py
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/channels.py
  hikari/events/channel_events.py
  hikari/events/message_events.py
  hikari/events/typing_events.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/stateful_cache.py
  hikari/impl/stateful_event_manager.py
  hikari/impl/stateless_cache.py
  hikari/intents.py
  hikari/utilities/cache.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_stateful_cache.py
  tests/hikari/impl/test_stateless_cache.py
  tests/hikari/test_channels.py
Labels: enhancement

#155 Task/debug is dead
  hikari/impl/bot.py
  hikari/impl/buckets.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/voice.py
  hikari/utilities/attr_extensions.py
  hikari/utilities/ux.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
Labels: bug, documentation, enhancement

#156 Add syntatic sugar to `async with` classes
  hikari/files.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/utilities/event_stream.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/test_files.py
  tests/hikari/utilities/test_event_stream.py
Labels: enhancement

#157 New rest docs
  docs/documentation.mako
  hikari/api/rest.py
Labels: documentation

#159 Fix CONTRIBUTING.md to remove references to dead branches
  CONTRIBUTING.md
Labels: documentation

#164 Modified `BotApp` to reallow disabling of intents.
  hikari/impl/bot.py
Labels: enhancement

#171 Document RELAY_ENABLED guild feature for large guilds.
  hikari/guilds.py
Labels: enhancement

#169 Remove unused Unavailable guild error
  hikari/errors.py
Labels: enhancement

#170 Make Member#premium_since mandatory.
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/utilities/cache.py
  tests/hikari/impl/test_entity_factory.py
Labels: blocked, documentation, enhancement

#173 Added colors back to import path.
  hikari/__init__.py
Labels: bug

#172 Added documentation about how to use Python's dictConfig incrementally.
  hikari/impl/bot.py
Labels: documentation

#167 Implemented `user` member on typing events.
  hikari/events/typing_events.py
  hikari/impl/event_factory.py
  tests/hikari/events/test_typing_events.py
Labels: bug, enhancement

#165 Added message author attributes to events and fixed typing.
  hikari/events/message_events.py
  tests/hikari/events/test_message_events.py
Labels: bug, enhancement

#174 Added the ability to mark files as spoilers
  hikari/files.py
Labels: enhancement

#175 Add `top_role` property to member
  hikari/guilds.py
  tests/hikari/test_guilds.py
Labels: enhancement

#178 Made flag enums lazily load, speeding up cache and event ops.
  hikari/channels.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/messages.py
  hikari/presences.py
  hikari/users.py
  hikari/utilities/cache.py
  tests/hikari/test_channels.py
Labels: optimization

#181 Fix mypy error
  hikari/utilities/aio.py
Labels: enhancement

#185 Optimize `shards` property
  hikari/impl/bot.py
Labels: enhancement

#177 Allow Color.of to accept string representation of an RGB Tuple
  hikari/colors.py
  tests/hikari/test_colors.py
Labels: enhancement, testing

#186 Add ability to disable checking for updates
  hikari/impl/bot.py
Labels: enhancement

#188 Fix incorrect encoding being sent
  hikari/impl/shard.py
Labels: bug

#191 Added new logic to shard that should hopefully detect random socket c…
  hikari/impl/rate_limits.py
  hikari/impl/shard.py
  tests/hikari/impl/test_rate_limits.py
  tests/hikari/impl/test_shard.py
Labels: bug

#195 Bugfix/windows os error
  hikari/config.py
  hikari/impl/bot.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/utilities/net.py
  hikari/utilities/ux.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/test_snowflake.py
Labels: bug, documentation, enhancement, testing

#196 Fixes edge case where messages in guilds had a None 'author' attribute
  hikari/events/message_events.py
  hikari/utilities/ux.py
Labels: bug, enhancement

#199 Added uvloop provisionally to linux only systems
  speedup-requirements.txt
Labels: dependencies, enhancement

#193 Added tests for utilities.ux
  hikari/api/rest.py
  hikari/presences.py
  hikari/utilities/ux.py
  tests/hikari/impl/test_shard.py
  tests/hikari/utilities/test_ux.py
Labels: bug, enhancement, testing

#200 Fix inconsistecy in cache naming
  hikari/api/cache.py
  hikari/events/message_events.py
  hikari/events/typing_events.py
  hikari/impl/stateful_cache.py
  hikari/impl/stateless_cache.py
  tests/hikari/events/test_typing_events.py
  tests/hikari/impl/test_stateful_cache.py
  tests/hikari/impl/test_stateless_cache.py
  tests/hikari/utilities/test_ux.py
Labels: enhancement

#206 Fix attribute linking in properties
  docs/documentation.mako
Labels: bug

#203 Added all missing docs on REST
  hikari/api/rest.py
  hikari/errors.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_rest.py
Labels: documentation

#215 Comparing applications.TeamMember with guilds.Member and users.User
  hikari/applications.py
  hikari/guilds.py
  tests/hikari/integration/__init__.py
  tests/hikari/integration/test_users_comparison.py
Labels: bug, enhancement, testing

#213 Improve error str and added code + message
  hikari/errors.py
  hikari/utilities/net.py
  tests/hikari/test_errors.py
  tests/hikari/utilities/test_net.py
Labels: enhancement

#214 Faster enum impl
  hikari/api/rest.py
  hikari/api/shard.py
  hikari/api/special_endpoints.py
  hikari/applications.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/errors.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/invites.py
  hikari/messages.py
  hikari/permissions.py
  hikari/presences.py
  hikari/users.py
  hikari/utilities/cache.py
  hikari/utilities/enums.py
  hikari/utilities/enums.pyi
  hikari/webhooks.py
  scripts/enum_benchmark.py
  tests/hikari/utilities/test_enums.py
Labels: enhancement, optimization

#216 Move reformat-code dependencies to dev-requirements
  dev-requirements.txt
  pipelines/flake8.nox.py
  pipelines/format.nox.py
  tests/hikari/utilities/test_net.py
Labels: enhancement

#217 Added RESTErrorCode
  hikari/errors.py
  hikari/utilities/net.py
Labels: enhancement

#222 Snowflakeish types are no longer compatible with 'str' directly.
  README.md
  hikari/snowflakes.py
Labels: documentation, enhancement, optimization

#221 Task/218 dm message event naming
  README.md
  hikari/api/cache.py
  hikari/events/channel_events.py
  hikari/events/message_events.py
  hikari/events/reaction_events.py
  hikari/events/typing_events.py
  hikari/impl/event_factory.py
  hikari/impl/stateful_cache.py
  hikari/impl/stateless_cache.py
  tests/hikari/events/test_message_events.py
  tests/hikari/events/test_typing_events.py
  tests/hikari/impl/test_stateful_cache.py
  tests/hikari/impl/test_stateless_cache.py
Labels: documentation, enhancement, testing

#223 Implemented ability to do 'resource.read()' directly as a shortcut.
  hikari/files.py
Labels: enhancement, optimization

#168 Migrate to V8 Gateway and REST API
  README.md
  hikari/__init__.py
  hikari/channels.py
  hikari/impl/bot.py
  hikari/impl/entity_factory.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/stateful_cache.py
  hikari/impl/stateful_event_manager.py
  hikari/presences.py
  hikari/urls.py
  hikari/utilities/cache.py
  hikari/utilities/ux.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/test_channels.py
  tests/hikari/utilities/test_ux.py
Labels: documentation, enhancement, priority, testing

#224 Disable intents from being None
  hikari/api/shard.py
  hikari/impl/bot.py
  hikari/impl/shard.py
  hikari/impl/stateful_guild_chunker.py
  hikari/traits.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_stateful_guild_chunker.py
Labels: enhancement

#230 Added support for color detection via COLORTERM env var.
  hikari/utilities/ux.py
Labels: enhancement

#229 Improved handling of bucket ratelimits in edge cases.
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: bug

#228 Added warnings for bad presence update payloads.
  .gitignore
  hikari/config.py
  hikari/impl/bot.py
  hikari/presences.py
  hikari/utilities/ux.py
Labels: documentation, enhancement

#233 Added trigger_typing() to TextChannel.
  hikari/channels.py
Labels: enhancement

#232 Fixes #231 - adds Member.presence property.
  hikari/guilds.py
Labels: enhancement

#238 Moved optinal arguments to `Other Parameters` sublist
  hikari/api/chunker.py
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/api/shard.py
  hikari/api/special_endpoints.py
  hikari/channels.py
  hikari/embeds.py
  hikari/events/guild_events.py
  hikari/events/message_events.py
  hikari/events/shard_events.py
  hikari/files.py
  hikari/impl/bot.py
  hikari/impl/special_endpoints.py
  hikari/messages.py
  hikari/traits.py
  hikari/utilities/cache.py
  hikari/utilities/data_binding.py
  hikari/webhooks.py
Labels: documentation

#239 Rename `hikari.utitlities.date` to `hikari.utilities.time`
  .flake8
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/files.py
  hikari/impl/bot.py
  hikari/impl/buckets.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/rate_limits.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/special_endpoints.py
  hikari/impl/stateful_guild_chunker.py
  hikari/sessions.py
  hikari/snowflakes.py
  hikari/utilities/net.py
  hikari/utilities/time.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_shard.py
  tests/hikari/utilities/test_time.py
Labels: enhancement

#236 Added codeclimate reporter to CI
  .codeclimate.yml
  .travis.yml
  README.md
Labels: devops

#240 Fix a unbound error
  hikari/files.py
  hikari/impl/bot.py
  hikari/impl/buckets.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/special_endpoints.py
  hikari/impl/stateful_guild_chunker.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_stateful_guild_chunker.py
Labels: bug

#244 Fix documentation issues
  docs/documentation.mako
  hikari/config.py
  hikari/impl/bot.py
  hikari/utilities/collections.py
Labels: bug

#246 Fix some inconsistencies across the library
  hikari/api/chunker.py
  hikari/impl/event_manager_base.py
  hikari/impl/shard.py
Labels: enhancement

#252 Fix DM_MESSAGES documentation to remove CHANNEL_CREATE
  hikari/intents.py
Labels: documentation
