Repository hikari-py/hikari, pull requests merged in 2020-11, with the labels that each got.

#342 More testing
  hikari/guilds.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/internal/test_enums.py
  tests/hikari/test_messages.py
Labels: testing

#340 New mention object and small cleanups
  hikari/impl/bot.py
  hikari/impl/entity_factory.py
  hikari/internal/collections.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_messages.py
Labels: enhancement

#347 Implement a lock to help ratelimiting handling
  hikari/impl/bot.py
  hikari/impl/buckets.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
Labels: bug

#352 Prebuilt documentation for faster loading times
  .gitignore
  docs/body.mako
  docs/config.mako
  docs/css.mako
  docs/documentation.mako
  docs/footer.mako
  docs/head.mako
  docs/html.mako
  docs/patched_pdoc.py
  docs/search.mako
  pipelines/pdoc3.nox.py
  scripts/prebuild_index.js
Labels: enhancement

#355 Fix removing files on pipelines
  pipelines/pytest.nox.py
  pipelines/utils.nox.py
Labels: enhancement

#357 Rename `create_crossposts` to `crosspost_message`
  hikari/api/rest.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#360 Add intent warning to `fetch_members`
  hikari/api/rest.py
Labels: documentation

#359 New webhook endpoints
  hikari/api/rest.py
  hikari/impl/rest.py
  hikari/internal/routes.py
  hikari/webhooks.py
  tests/hikari/test_webhooks.py
Labels: enhancement

#365 Refactor ID sequences into Snowflakes
  hikari/api/chunker.py
  hikari/api/rest.py
  hikari/api/shard.py
  hikari/channels.py
  hikari/errors.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/stateful_guild_chunker.py
  hikari/impl/stateless_guild_chunker.py
  hikari/messages.py
  hikari/snowflakes.py
  hikari/webhooks.py
Labels: enhancement

#367 Fix documentation linking
  docs/documentation.mako
  hikari/api/event_dispatcher.py
  hikari/api/rest.py
  hikari/applications.py
  hikari/events/lifetime_events.py
  hikari/internal/data_binding.py
  hikari/messages.py
Labels: documentation

#362 Moved cache configuration to own class
  hikari/config.py
  hikari/impl/bot.py
  hikari/impl/stateful_cache.py
  tests/hikari/impl/test_stateful_cache.py
Labels: enhancement

#370 Feature/cache configuration
  hikari/api/cache.py
  hikari/api/event_factory.py
  hikari/config.py
  hikari/events/channel_events.py
  hikari/events/guild_events.py
  hikari/events/member_events.py
  hikari/events/message_events.py
  hikari/events/role_events.py
  hikari/events/user_events.py
  hikari/events/voice_events.py
  hikari/impl/bot.py
  hikari/impl/event_factory.py
  hikari/impl/stateful_cache.py
  hikari/impl/stateful_event_manager.py
  hikari/impl/stateless_cache.py
  hikari/impl/stateless_event_manager.py
  tests/hikari/events/test_channel_events.py
  tests/hikari/events/test_guild_events.py
  tests/hikari/events/test_member_events.py
  tests/hikari/events/test_message_events.py
  tests/hikari/events/test_role_events.py
  tests/hikari/events/test_voice_events.py
  tests/hikari/impl/test_stateful_cache.py
  tests/hikari/impl/test_stateful_event_manager.py
  tests/hikari/impl/test_stateless_cache.py
  tests/hikari/impl/test_stateless_event_manager.py
Labels: enhancement

#371 Fix logging
  hikari/embeds.py
  hikari/impl/bot.py
  hikari/internal/ux.py
Labels: enhancement

#372 Fix message reference documentation and object
  hikari/impl/entity_factory.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#369 Switch to using `x-ratelimit-reset-after` as reset_after
  hikari/applications.py
  hikari/impl/buckets.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/time.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/internal/test_time.py
Labels: enhancement

#375 Fix bot.heartbeat_latency to return the average instead of the sum
  hikari/impl/bot.py
Labels: bug

#374 Fix bug on wait_for so that timeouts remove it from the waiters_set
  hikari/impl/event_manager_base.py
Labels: bug

#378 Switch pipelines to Github Actions
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/docker.yml
  .travis.yml
  README.md
  hikari/_about.py
  pipelines/config.py
  pipelines/format.nox.py
  pipelines/pytest.nox.py
  scripts/deploy-manually.sh
  scripts/deploy-pages.sh
  scripts/deploy.sh
  scripts/deploy_webhook.py
  scripts/test-job.sh
Labels: devops

#373 Implement support for inline replies
  hikari/api/rest.py
  hikari/channels.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/messages.py
  hikari/urls.py
  pipelines/pdoc3.nox.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_channels.py
  tests/hikari/test_messages.py
Labels: enhancement

#379 Run CI on branches and pull_requests only
  .github/workflows/ci.yml
  scripts/deploy_webhook.py
Labels: devops
