Repository hikari-py/hikari, pull requests merged in 2021-10, with the labels that each got.

#804 Documentation additions and fixes
  CONTRIBUTING.md
  changes/804.doc.md
  changes/804.feature.md
  hikari/api/event_manager.py
  hikari/api/special_endpoints.py
  hikari/guilds.py
  hikari/impl/bot.py
Labels: documentation

#819 Fix how remove_reaction's example targeted users
  hikari/messages.py
Labels: documentation, skip-fragment-check

#816 Remove RESTErrorCode enum
  changes/816.breaking.md
  hikari/errors.py
  hikari/internal/net.py
  tests/hikari/test_errors.py
Labels: enhancement, breaking

#820 Remove Unique pattern and hashing from Overwrites
  changes/820.breaking.md
  hikari/channels.py
  hikari/impl/rest.py
  hikari/interactions/base_interactions.py
  hikari/interactions/command_interactions.py
  hikari/interactions/component_interactions.py
Labels: breaking

#809 Implement GuildJoinEvent
  changes/809.breaking.md
  changes/809.feature.md
  hikari/api/event_factory.py
  hikari/events/guild_events.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
Labels: enhancement, breaking

#821 Add `allow` and `deny` to PermissionOverwrite's repr
  hikari/channels.py
Labels: enhancement, skip-fragment-check

#817 Fix BulkDeleteError showing incorrect values
  changes/817.bugfix.md
  hikari/impl/rest.py
Labels: bug
