Repository hikari-py/hikari, pull requests merged in 2021-02, with the labels that each got.

#463 Even more tests and fixes
  hikari/api/event_manager.py
  hikari/audit_logs.py
  hikari/event_stream.py
  hikari/impl/bot.py
  hikari/impl/entity_factory.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_audit_logs.py
  tests/hikari/test_event_stream.py
Labels: enhancement, testing

#468 Add helpful sha1 on SNAPSHOT versions
  hikari/cli.py
Labels: enhancement

#469 Rewrite `protocol.Protocol` to a typing extension
  hikari/internal/attr_extensions.py
  hikari/internal/enums.py
  hikari/internal/enums.pyi
  hikari/internal/fast_protocol.py
  hikari/internal/fast_protocol.pyi
  hikari/traits.py
  scripts/protocol_benchmark.py
  tests/hikari/internal/test_typing_extensions.py
Labels: bug

#473 Enums consistency changes/fixes
  hikari/internal/enums.py
  tests/hikari/internal/test_enums.py
  tests/hikari/test_applications.py
  tests/hikari/test_channels.py
  tests/hikari/test_guilds.py
  tests/hikari/test_intents.py
  tests/hikari/test_invites.py
  tests/hikari/test_messages.py
  tests/hikari/test_presences.py
  tests/hikari/test_users.py
  tests/hikari/test_webhooks.py
Labels: bug, enhancement

#471 Even more testing
  hikari/api/cache.py
  tests/hikari/test_audit_logs.py
Labels: testing

#476 Send a full heartbeat on a heartbeat request, not just an ACK
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: bug

#475 Fix mis-usage of PAYLOAD_ZLIB_STREAM where TRANSPORT_ZLIB_STREAM is being referred to
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: bug

#481 Add the new message types
  hikari/messages.py
Labels: enhancement

#482 Add slash command related oauth2 scopes.
  hikari/applications.py
Labels: enhancement

#483 Add get_guilds_view method to cache to match get_guild
  hikari/api/cache.py
  hikari/impl/cache.py
  tests/hikari/impl/test_cache.py
Labels: enhancement

#487 Fix RESTApp.acquire return typing
  hikari/impl/rest.py
Labels: bug

#484 Add close method to the BotAware trait
  hikari/traits.py
Labels: enhancement

#479 Add the use application commands permission
  hikari/permissions.py
Labels: enhancement

#477 Fix MYPY typing of Embed.colour alias
  hikari/embeds.py
Labels: bug

#490 Add missing documentation
  hikari/api/rest.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/events/channel_events.py
  hikari/events/typing_events.py
  hikari/guilds.py
  hikari/messages.py
  hikari/users.py
  hikari/webhooks.py
  tests/hikari/test_guilds.py
Labels: documentation

#488 Fixed some todos
  hikari/api/cache.py
  hikari/applications.py
  hikari/internal/enums.py
  hikari/webhooks.py
  tests/hikari/hikari_test_helpers.py
Labels: enhancement

#489 Prevent linking to `about`
  docs/documentation.mako
Labels: documentation
