Repository hikari-py/hikari, pull requests merged in 2021-12, with the labels that each got.

#928 Fix reposition_roles using the wrong route
  changes/928.bugfix.md
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: bug

#920 Add min_value and max_value to CommandOption
  changes/920.feature.md
  hikari/commands.py
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#931 Fix ROLE_ICON cdn route
  changes/931.bugfix.md
  hikari/internal/routes.py
Labels: bug

#934 Dont assign dependabot pull requests
  .github/dependabot.yml
Labels: devops, skip-fragment-check

#935 Fix logic to ensure no CHANGELOG files exist
  scripts/deploy.sh
Labels: devops, skip-fragment-check

#930 Fix PartialSticker.image_url not passing the hash as a string
  changes/930.bugfix.md
  hikari/internal/routes.py
  hikari/stickers.py
  tests/hikari/test_stickers.py
Labels: bug

#944 Add security policy
  SECURITY.md
Labels: skip-fragment-check

#939 Add flags to Application
  changes/939.feature.md
  hikari/applications.py
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#940 Implement member timeout
  changes/940.feature.md
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/cache.py
  hikari/permissions.py
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/integration/test_users_comparison.py
  tests/hikari/test_guilds.py
  tests/hikari/test_permissions.py
Labels: enhancement

#933 Fix some bugs in message deserialization
  changes/933.bugfix.md
  hikari/impl/entity_factory.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug
