Repository hikari-py/hikari, pull requests merged in 2021-09, with the labels that each got.

#763 Feature/747 retry request on 5xx error
  .gitignore
  CHANGELOG.md
  hikari/impl/bot.py
  hikari/impl/rest.py
  hikari/impl/rest_bot.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_rest_bot.py
Labels: enhancement

#752 Add a web dashboard example
  .gitignore
  examples/simple_dashboard/__init__.py
  examples/simple_dashboard/requirements.txt
  examples/simple_dashboard/simple_dashboard.bat
  examples/simple_dashboard/simple_dashboard.py
  examples/simple_dashboard/simple_dashboard.sh
  mypy.ini
Labels: enhancement

#770 Add is_for_emoji methods to the relevant reaction events
  hikari/events/reaction_events.py
  tests/hikari/events/test_reaction_events.py
Labels: enhancement

#773 Fix spelling mistakes in documentation
  hikari/api/rest.py
  hikari/config.py
Labels: documentation

#772 Add information about versioning scheme and deprecation
  CONTRIBUTING.md
  docs/config.mako
  pipelines/codespell.nox.py
  pipelines/config.py
  pipelines/format.nox.py
Labels: documentation

#778 Remove deprecated `BotApp`
  CONTRIBUTING.md
  changes/778.removal.md
  hikari/__init__.py
  hikari/__init__.pyi
  hikari/impl/bot.py
  hikari/traits.py
  tests/hikari/test_presences.py
Labels: a lost feature

#782 Remove internal changelog fragments
  .github/workflows/fragments-check.yml
  CONTRIBUTING.md
  changes/762.internal.md
  changes/TEMPLATE.jinja2
  pyproject.toml
Labels: skip-fragment-check

#779 Fix `embeds` type error in edit_message, fix `embeds` JSON serialize …
  changes/779.bugfix.md
  hikari/impl/rest.py
Labels: bug

#783 Improve typing for messages and message update methods
  changes/783.bugfix.md
  hikari/events/message_events.py
  hikari/impl/entity_factory.py
  hikari/messages.py
  tests/hikari/events/test_message_events.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_messages.py
Labels: bug, breaking

#785 Cast `CommandOption.value` to a `Snowflake` for types 6-9
  changes/785.bugfix.md
  hikari/impl/entity_factory.py
  hikari/interactions/command_interactions.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug

#781 Add tests for some more modules
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fragments-check.yml
  .github/workflows/prepare-release.yml
  coverage.ini
  hikari/api/rest.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/voice.py
  hikari/internal/data_binding.py
  hikari/internal/routes.py
  tests/hikari/events/test_reaction_events.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_interaction_server.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_rest_bot.py
  tests/hikari/impl/test_voice.py
  tests/hikari/internal/test_data_binding.py
  tests/hikari/test_channels.py
  tests/hikari/test_guilds.py
  tests/hikari/test_stickers.py
  tests/hikari/test_webhooks.py
Labels: testing, skip-fragment-check

#789 Fix prepare release workflow
  .github/workflows/ci.yml
  .github/workflows/prepare-release.yml
  changes/778.removal.md
  scripts/prepare-release.sh
Labels: devops, skip-fragment-check

#788 Prevent double linking embed resources, which causes them to upload twice
  changes/788.bugfix.md
  hikari/embeds.py
Labels: bug

#792 Small doc fixes around menu value ranges
  CHANGELOG.md
  CONTRIBUTING.md
  hikari/api/special_endpoints.py
  hikari/messages.py
Labels: documentation, skip-fragment-check

#791 More workflow fixes
  .github/workflows/ci.yml
  .github/workflows/prepare-release.yml
  scripts/deploy-manually.sh
  scripts/deploy-webhook.sh
  scripts/deploy.sh
Labels: devops, skip-fragment-check

#793 Add check for trailing whitespaces
  .github/workflows/ci.yml
  pipelines/format.nox.py
Labels: devops, skip-fragment-check

#799 Thread permission changes
  changes/799.breaking.md
  hikari/permissions.py
  pyproject.toml
  tests/hikari/test_permissions.py
Labels: enhancement, breaking

#800 Add new channel_types field to CommandOption
  CHANGELOG.md
  changes/800.feature.md
  hikari/commands.py
  hikari/impl/entity_factory.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#798 Add new START_EMBEDDED_ACTIVITIES permission
  changes/798.feature.md
  hikari/permissions.py
  tests/hikari/test_permissions.py
Labels: enhancement

#803 Update website links
  README.md
  docs/config.mako
  hikari/_about.py
  pages/index.html
Labels: documentation, skip-fragment-check

#787 Implement form builder to allow re-usage of forms
  changes/787.bugfix.md
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/data_binding.py
  tests/hikari/impl/test_rest.py
  tests/hikari/internal/test_data_binding.py
Labels: bug

#805 Persist CNAME file between between page builds
  pages/CNAME
Labels: documentation, skip-fragment-check

#807 Move release CI to separate file
  .github/workflows/ci.yml
  .github/workflows/release.yml
  pipelines/format.nox.py
Labels: devops, skip-fragment-check
