Repository hikari-py/hikari, pull requests merged in 2021-03, with the labels that each got.

#496 Update README
  README.md
Labels: documentation

#497 Remove debug from the VoiceConnection abc
  hikari/api/voice.py
Labels: bug

#492 Add in __index__ overrides alongside __int__ overrides
  hikari/internal/enums.py
  hikari/internal/enums.pyi
  hikari/snowflakes.py
  tests/hikari/internal/test_enums.py
  tests/hikari/test_snowflake.py
Labels: enhancement

#504 Temporarily remove emoji validation and unicode_names
  hikari/emojis.py
Labels: bug

#478 Improve the UX around RESTClient.delete_messages
  hikari/api/rest.py
  hikari/impl/rest.py
  hikari/snowflakes.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#494 Deprecation utils
  docs/documentation.mako
  hikari/events/base_events.py
  hikari/internal/deprecation.py
  hikari/internal/net.py
  hikari/internal/ux.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/internal/test_deprecation.py
Labels: enhancement

#506 Switch to minified map in twemoji pipeline
  scripts/test_twemoji_mapping.py
Labels: devops

#505 Enable CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: devops

#480 Add application flags and ID to the ready event.
  hikari/applications.py
  hikari/events/shard_events.py
  hikari/impl/event_factory.py
Labels: enhancement

#510 Add application tos and privacy policy urls
  hikari/applications.py
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#511 Fix specifying action_type in fetch_audit_log
  hikari/api/rest.py
  hikari/audit_logs.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/data_binding.py
Labels: bug
