Repository hikari-py/hikari, pull requests merged in 2021-04, with the labels that each got.

#512 Replace guild region with voice channel rtc region + bug fix
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/data_binding.py
  hikari/templates.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_guilds.py
Labels: a lost feature, bug, enhancement

#528 Add new Suppress Guild Reminder flag
  hikari/guilds.py
Labels: enhancement

#522 Remove RPC_API
  hikari/applications.py
Labels: a lost feature

#520 Document missing message types
  hikari/messages.py
Labels: enhancement

#518 Add new "EPHEMERAL" and "LOADING" message types
  hikari/messages.py
Labels: enhancement

#530 Document Attachment content type
  hikari/impl/entity_factory.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_messages.py
Labels: enhancement

#525 "region" was renamed to "rtc_region" and made nullable in payloads; remove warning from WATCHING
  hikari/impl/entity_factory.py
  hikari/presences.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug, enhancement

#521 Document "raw_endpoint" and "endpoint" as being nullable
  hikari/events/voice_events.py
  hikari/impl/voice.py
  tests/hikari/events/test_voice_events.py
Labels: bug

#516 Switch python3.10 to dev version
  .github/workflows/ci.yml
  speedup-requirements.txt
Labels: devops

#519 Add intent requirement to only be enabled in dashboard
  hikari/api/rest.py
Labels: documentation

#531 Document the re-parsing of allowed_mentions on non-embed content
  hikari/api/rest.py
  hikari/messages.py
  hikari/webhooks.py
Labels: documentation

#534 Document unknown guild template error code
  hikari/errors.py
Labels: enhancement

#495 Rename `format_x` to `make_x_url`
  hikari/applications.py
  hikari/channels.py
  hikari/guilds.py
  hikari/invites.py
  hikari/messages.py
  hikari/users.py
  hikari/webhooks.py
  tests/hikari/test_applications.py
  tests/hikari/test_channels.py
  tests/hikari/test_guilds.py
  tests/hikari/test_messages.py
  tests/hikari/test_users.py
Labels: bug

#543 Remove preview_asset_hash as Discord no longer send it
  hikari/impl/entity_factory.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
Labels: a lost feature

#542 Implement new fetch_webhook_message
  hikari/api/rest.py
  hikari/impl/rest.py
  hikari/internal/routes.py
  hikari/webhooks.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_webhooks.py
Labels: enhancement

#536 Fix some todos
  hikari/api/shard.py
  hikari/events/channel_events.py
  hikari/files.py
  hikari/guilds.py
  hikari/impl/cache.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager_base.py
  hikari/impl/shard.py
  hikari/impl/voice.py
  hikari/internal/cache.py
  hikari/internal/enums.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_shard.py
  tests/hikari/internal/test_collections.py
Labels: enhancement

#529 Implement new "video_quality_mode"
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/channels.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#549 Remove the user system flag
  hikari/users.py
Labels: a lost feature

#550 Remove undocumented application flags
  hikari/applications.py
Labels: a lost feature

#551 Add presence activity buttons
  hikari/impl/entity_factory.py
  hikari/internal/cache.py
  hikari/presences.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#548 Update fetch welcome screen docs and behaviour
  hikari/api/rest.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: documentation

#509 OAuth2 feature: endpoint logic and REST cli internal token strategy
  README.md
  hikari/__init__.py
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/applications.py
  hikari/emojis.py
  hikari/guilds.py
  hikari/impl/bot.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/data_binding.py
  hikari/internal/routes.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_applications.py
Labels: enhancement

#554 Fix rtc_region edge case
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug

#559 Fix pipelines to install wheel and setuptools
  .github/workflows/ci.yml
  speedup-requirements.txt
Labels: devops

#556 Move away from distutils as it has been deprecated
  .idea/fileTemplates/Python Module.py
  docs/config.mako
  hikari/colors.py
  hikari/emojis.py
  hikari/impl/rest.py
  hikari/internal/deprecation.py
  hikari/internal/fast_protocol.pyi
  hikari/internal/ux.py
  tests/hikari/internal/test_ux.py
Labels: enhancement

#545 Handle unknown entities
  hikari/api/entity_factory.py
  hikari/audit_logs.py
  hikari/errors.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager_base.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_audit_logs.py
Labels: enhancement

#561 Only account for specific major param combinations
  hikari/internal/routes.py
  tests/hikari/internal/test_routes.py
Labels: bug

#563 Freeze pytest to fix CPython 3.10 issues
  dev-requirements.txt
Labels: devops
