Repository hikari-py/hikari, pull requests merged in 2021-08, with the labels that each got.

#706 Reformat generated stubs
  hikari/__init__.pyi
  hikari/events/__init__.pyi
  hikari/interactions/__init__.pyi
  pipelines/format.nox.py
  pipelines/mypy.nox.py
Labels: devops

#707 Fix incorrect JSON arguments in edit_guild
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: bug

#715 Bump coverage to 6.0b1
  dev-requirements.txt
Labels: dependencies, python

#714 Improve 50035 400 error reprs
  hikari/errors.py
  hikari/internal/data_binding.py
  hikari/internal/net.py
  tests/hikari/internal/test_net.py
  tests/hikari/test_errors.py
Labels: enhancement

#710 CommandInteractionOption typing fix
  hikari/interactions/commands.py
Labels: bug

#686 Improve typing/strictness of Emoji classes
  hikari/api/rest.py
  hikari/emojis.py
  hikari/events/reaction_events.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/rest.py
  hikari/internal/cache.py
  hikari/messages.py
  tests/hikari/events/test_reaction_events.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_emojis.py
  tests/hikari/test_messages.py
Labels: bug, enhancement, breaking

#657 Remove a couple type ignores + cleanup CacheMappingView
  hikari/api/cache.py
  hikari/config.py
  hikari/files.py
  hikari/internal/aio.py
  hikari/internal/cache.py
Labels: bug, enhancement

#719 Account for embed attachments in InteractionMessageBuilder.build
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_special_endpoints.py
Labels: bug

#723 Support the Number application command option type
  hikari/interactions/commands.py
Labels: enhancement

#703 Fix some bugs in voice impl
  hikari/api/voice.py
  hikari/impl/voice.py
  tests/hikari/impl/test_voice.py
Labels: bug, enhancement, breaking

#708 Add some simplifications for external importers
  .flake8
  hikari/__init__.py
  hikari/__init__.pyi
  hikari/api/__init__.py
  hikari/api/__init__.pyi
  hikari/impl/__init__.py
  hikari/impl/__init__.pyi
  pipelines/mypy.nox.py
Labels: enhancement

#743 Mark ci-done as failed when past jobs failed
  .github/workflows/ci.yml
Labels: devops

#740 Fix DeprecationWarnings on python 3.10
  hikari/internal/aio.py
  tests/hikari/impl/test_rest_bot.py
  tests/hikari/internal/test_aio.py
Labels: bug

#739 Install speedups in mypy pipeline to load stubs for them
  hikari/internal/time.py
  pipelines/mypy.nox.py
Labels: devops

#737 Document new REST Codes
  hikari/errors.py
  tests/hikari/test_errors.py
Labels: enhancement

#738 Fix CDN properties not ending with "_url"
  hikari/invites.py
  hikari/webhooks.py
  tests/hikari/test_webhooks.py
Labels: breaking

#742 Consistency fixes for `__all__` usages
  hikari/api/interaction_server.py
  hikari/events/interaction_events.py
  hikari/files.py
  hikari/impl/interaction_server.py
  hikari/impl/rest_bot.py
  hikari/internal/ed25519.py
  hikari/internal/mentions.py
Labels: refactor

#735 Add codespell pipeline to CI
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  dev-requirements.txt
  hikari/api/cache.py
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/colors.py
  hikari/errors.py
  hikari/events/guild_events.py
  hikari/guilds.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/internal/cache.py
  hikari/internal/enums.py
  hikari/internal/spel.py
  hikari/internal/time.py
  hikari/iterators.py
  pipelines/codespell.nox.py
  pipelines/format.nox.py
  tests/hikari/impl/test_shard.py
  tests/hikari/test_undefined.py
  tests/hikari/test_webhooks.py
Labels: devops

#749 Remove application command events
  hikari/api/event_factory.py
  hikari/events/interaction_events.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  tests/hikari/events/test_interaction_events.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
Labels: a lost feature

#726 Fix dm_channel_id cache component check
  hikari/config.py
  hikari/impl/cache.py
  tests/hikari/impl/test_cache.py
Labels: bug, enhancement

#720 Implement Slash Command Permissions
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/commands.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/routes.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/test_commands.py
Labels: enhancement

#736 Implement new sticker models + routes
  hikari/__init__.py
  hikari/__init__.pyi
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/emojis.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/cache.py
  hikari/internal/routes.py
  hikari/messages.py
  hikari/permissions.py
  hikari/stickers.py
  hikari/webhooks.py
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#755 Fix typo in docstring for Colorish
  hikari/colors.py
Labels: documentation

#753 Fix deployment CI
  scripts/deploy-manually.sh
  scripts/deploy-pages.sh
  scripts/deploy-webhook.sh
  scripts/deploy.sh
Labels: devops

#754 Add sticker methods to PartialGuild
  CHANGELOG.md
  hikari/api/rest.py
  hikari/guilds.py
  tests/hikari/test_guilds.py
Labels: enhancement
