Repository hikari-py/hikari, pull requests merged in 2021-06, with the labels that each got.

#630 Fix edit_permission_overwrites route using wrong method
  hikari/impl/rest.py
  hikari/internal/routes.py
  tests/hikari/impl/test_rest.py
Labels: bug

#633 Allow a datetime to be passed for request_to_speak
  hikari/api/rest.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#632 Improve typing of Application (returned by fetch_application)
  hikari/applications.py
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#639 Reset shard backoff if nothing went wrong when shutting down
  hikari/impl/shard.py
Labels: bug

#643 Separate member and author on GuildMessage* events
  hikari/events/message_events.py
  hikari/messages.py
  tests/hikari/events/test_message_events.py
Labels: breaking, bug

#635 Move helpful guild properties to the Guild object
  hikari/guilds.py
  tests/hikari/test_guilds.py
Labels: enhancement

#644 Add mention properties to GuildChannel and PartialRole
  hikari/channels.py
  hikari/guilds.py
  tests/hikari/test_channels.py
  tests/hikari/test_guilds.py
Labels: enhancement

#645 Split iso8601_datetime_string_to_datetime into slow and fast
  hikari/internal/time.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/test_shard.py
  tests/hikari/internal/test_time.py
Labels: enhancement

#648 Document new 20031 error code
  hikari/errors.py
Labels: enhancement

#649 Replace json.* with data_binding.json_* where appropriate
  hikari/impl/shard.py
Labels: enhancement

#653 Remove outdated gateway related create message limit warnings
  hikari/api/rest.py
  hikari/channels.py
  hikari/messages.py
  hikari/users.py
Labels: documentation

#656 Add __init__.pyi files to git to help mypy when downloading from git
  .github/workflows/ci.yml
  .gitignore
  hikari/__init__.pyi
  hikari/events/__init__.pyi
  pipelines/mypy.nox.py
Labels: devops, enhancement

#659 remove settability from Unique.id's interface + small refactor
  hikari/applications.py
  hikari/channels.py
  hikari/embeds.py
  hikari/guilds.py
  hikari/snowflakes.py
  tests/hikari/test_applications.py
  tests/hikari/test_channels.py
  tests/hikari/test_guilds.py
Labels: breaking

#660 introduce REST filled DM Channel ID cache resource
  hikari/api/cache.py
  hikari/applications.py
  hikari/config.py
  hikari/guilds.py
  hikari/impl/bot.py
  hikari/impl/cache.py
  hikari/impl/rest.py
  hikari/internal/cache.py
  hikari/users.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_applications.py
  tests/hikari/test_guilds.py
  tests/hikari/test_users.py
Labels: enhancement

#661 Delay initialisation of BotApp._closing_event and use it as ._closed
  hikari/impl/bot.py
  tests/hikari/impl/test_bot.py
Labels: bug

#627 Add a token type property to the rest interface to allow for token introspection
  hikari/api/rest.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#664 Update uvloop section to include UNIX systems
  README.md
Labels: documentation

#666 Remove return from subscribe calls
  hikari/api/event_manager.py
  hikari/impl/bot.py
  hikari/impl/event_manager_base.py
  tests/hikari/impl/test_event_manager_base.py
Labels: breaking, enhancement

#665 Add sending multiple embeds on create and edit message
  hikari/api/rest.py
  hikari/channels.py
  hikari/impl/rest.py
  hikari/messages.py
  hikari/users.py
  hikari/webhooks.py
  tests/hikari/test_channels.py
  tests/hikari/test_messages.py
  tests/hikari/test_users.py
Labels: bug, enhancement

#668 Remove incorrect documentation of 400 caused by allowed mentions
  hikari/api/rest.py
  hikari/channels.py
  hikari/messages.py
  hikari/users.py
  hikari/webhooks.py
Labels: documentation

#641 Improve loop acquisition in BotApp.run
  hikari/impl/bot.py
  hikari/impl/event_manager_base.py
  hikari/internal/aio.py
  tests/hikari/__init__.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_shard.py
  tests/hikari/internal/test_aio.py
Labels: bug

#669 Do not send "embeds" in message create payloads when not specified
  hikari/impl/rest.py
Labels: enhancement

#673 Remove unnecessary typing casts
  hikari/files.py
  hikari/internal/aio.py
  hikari/internal/attr_extensions.py
  hikari/iterators.py
Labels: enhancement

#672 Add new rest error codes
  hikari/errors.py
Labels: enhancement

#671 Document new guild features
  hikari/guilds.py
Labels: enhancement

#674 Default content to None when empty string
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#663 Fix lifetime events not dispatching
  hikari/impl/bot.py
  hikari/impl/shard.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_shard.py
Labels: breaking, bug

#679 Add ci-done job
  .github/workflows/ci.yml
Labels: devops

#637 Add channel methods
  hikari/api/rest.py
  hikari/channels.py
  hikari/impl/rest.py
  tests/hikari/test_channels.py
Labels: breaking, bug, enhancement

#681 Use Signature's eval_str argument in resolve_signature (3.10+ specific)
  hikari/internal/reflect.py
  tests/hikari/internal/test_reflect.py
Labels: optimization

#683 Add artificial user_id property to BanCreateEvent
  hikari/events/guild_events.py
Labels: enhancement

#685 Move event_stream to event_manager api and impl modules
  hikari/api/event_manager.py
  hikari/event_stream.py
  hikari/files.py
  hikari/impl/bot.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/test_event_stream.py
Labels: breaking

#687 Only resolve type hints in @listen when necessary
  hikari/impl/event_manager_base.py
  tests/hikari/impl/test_event_manager_base.py
Labels: bug, enhancement
