Repository hikari-py/hikari, pull requests merged in 2021-01, with the labels that each got.

#416 Fix usage/setting of bot._is_alive and invalid channel type assertions
  hikari/channels.py
  hikari/events/channel_events.py
  hikari/events/message_events.py
  hikari/events/typing_events.py
  hikari/impl/bot.py
Labels: bug

#388 Cache refactors
  hikari/api/cache.py
  hikari/impl/stateful_cache.py
  hikari/impl/stateful_event_manager.py
  hikari/impl/stateless_cache.py
  hikari/internal/cache.py
  hikari/internal/collections.py
  hikari/undefined.py
  hikari/undefined.pyi
  hikari/users.py
  tests/hikari/impl/test_stateful_cache.py
  tests/hikari/impl/test_stateful_event_manager.py
  tests/hikari/internal/test_collections.py
Labels: enhancement

#417 Link to discussions in issue form
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#421 Seperate `reply` and `respond` in message
  README.md
  examples/hello_world/hello_world.py
  examples/image_resources/image_resources.py
  hikari/api/rest.py
  hikari/channels.py
  hikari/emojis.py
  hikari/impl/rest.py
  hikari/messages.py
  hikari/users.py
  pages/index.html
  tests/hikari/impl/test_rest.py
  tests/hikari/test_channels.py
  tests/hikari/test_messages.py
  tests/hikari/test_users.py
Labels: enhancement

#412 Remove guild chunker and add cache configuration
  .flake8
  hikari/api/cache.py
  hikari/api/guild_chunker.py
  hikari/config.py
  hikari/impl/bot.py
  hikari/impl/cache.py
  hikari/impl/event_manager_base.py
  hikari/impl/guild_chunker.py
  hikari/impl/shard.py
  hikari/impl/stateful_event_manager.py
  hikari/impl/stateless_cache.py
  hikari/impl/stateless_event_manager.py
  hikari/impl/stateless_guild_chunker.py
  hikari/impl/voice.py
  hikari/internal/net.py
  hikari/messages.py
  hikari/traits.py
  pages/index.html
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_guild_chunker.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_stateful_event_manager.py
  tests/hikari/impl/test_stateless_cache.py
  tests/hikari/impl/test_stateless_event_manager.py
  tests/hikari/impl/test_stateless_guild_chunker.py
Labels: enhancement

#423 Reply cleanups
  hikari/api/rest.py
  hikari/channels.py
  hikari/impl/rest.py
  hikari/messages.py
  hikari/users.py
  tests/hikari/test_channels.py
  tests/hikari/test_messages.py
  tests/hikari/test_users.py
Labels: enhancement

#426 Freeze dev version to SNAPSHOT
  docs/html.mako
  hikari/_about.py
  hikari/banner.txt
Labels: enhancement

#425 Feature/traits fix
  .flake8
  hikari/api/cache.py
  hikari/api/chunker.py
  hikari/channels.py
  hikari/config.py
  hikari/events/channel_events.py
  hikari/events/guild_events.py
  hikari/events/member_events.py
  hikari/events/message_events.py
  hikari/events/typing_events.py
  hikari/guilds.py
  hikari/impl/bot.py
  hikari/impl/cache.py
  hikari/impl/event_manager.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/stateful_guild_chunker.py
  hikari/impl/stateless_cache.py
  hikari/impl/stateless_event_manager.py
  hikari/impl/stateless_guild_chunker.py
  hikari/impl/voice.py
  hikari/internal/net.py
  hikari/internal/ux.py
  hikari/messages.py
  hikari/traits.py
  pages/index.html
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_stateful_guild_chunker.py
  tests/hikari/impl/test_stateless_cache.py
  tests/hikari/impl/test_stateless_event_manager.py
  tests/hikari/impl/test_stateless_guild_chunker.py
  tests/hikari/test_channels.py
  tests/hikari/test_guilds.py
Labels: enhancement

#429 Fix pypi version detection and rename some attributes
  hikari/api/rest.py
  hikari/cli.py
  hikari/events/guild_events.py
  hikari/impl/event_manager.py
  hikari/internal/ux.py
  pipelines/pages.nox.py
  tests/hikari/impl/test_event_manager.py
Labels: enhancement

#432 Fix generated nonces for guild chunking going over the length limit
  hikari/impl/event_manager.py
  tests/hikari/impl/test_event_manager.py
Labels: bug

#433 ignore redundant ON_GUILD_INTEGRATIONS_UPDATE gateway event
  hikari/impl/event_manager.py
  tests/hikari/impl/test_event_manager.py
Labels: enhancement

#419 Rename EventDispatcher to EventManager and add a public raw event consumer system
  hikari/api/event_factory.py
  hikari/api/event_manager.py
  hikari/event_stream.py
  hikari/impl/bot.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  hikari/impl/event_manager_base.py
  hikari/impl/shard.py
  hikari/impl/voice.py
  hikari/traits.py
  hikari/webhooks.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_shard.py
  tests/hikari/test_event_stream.py
Labels: enhancement, optimization

#435 Improve search and cleanup docs
  .github/workflows/ci.yml
  docs/body.mako
  docs/config.mako
  docs/css.mako
  docs/documentation.mako
  docs/footer.mako
  docs/head.mako
  docs/html.mako
  docs/patched_pdoc.py
  docs/search.mako
  hikari/api/cache.py
  hikari/api/voice.py
  pages/index.html
  pipelines/pages.nox.py
  scripts/prebuild_index.js
Labels: documentation, enhancement

#443 Move deploy to ci.yml and only trigger when all other jobs succeeded
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/docker.yml
Labels: devops

#444 Add proxy resource to EmbedVideo and fix handling of None in embed resources.
  hikari/embeds.py
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_embeds.py
Labels: bug, enhancement

#447 Change black's include pattern to include .pyi files
  hikari/undefined.pyi
  pyproject.toml
Labels: devops

#441 Add a member object return to rest.edit_member
  hikari/api/rest.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#446 Enable python 3.10 ci
  .github/workflows/ci.yml
Labels: devops

#440 Add the welcome channel related models and REST endpoints
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/routes.py
  hikari/invites.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#448 Fix handling of "cover_image" in message application deserialization
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug

#449 Fix how we're provisionally setting the coroutine tracking depth
  hikari/impl/bot.py
Labels: bug

#451 Bump mypy to 0.800 and fix issues
  dev-requirements.txt
  hikari/config.py
  hikari/impl/cache.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/cache.py
Labels: dependencies

#456 Fix permissions being mishandled in audit logs and incorrect change keys
  hikari/audit_logs.py
  hikari/impl/entity_factory.py
  hikari/internal/enums.py
  hikari/internal/enums.pyi
  tests/hikari/impl/test_entity_factory.py
Labels: bug

#455 Add entities and rest endpoints for guild member screening
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  hikari/internal/routes.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#454 Replace typing.cast with assert statement where possible
  hikari/api/rest.py
  hikari/events/base_events.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/messages.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#458 Make nickname optional if not available
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/internal/cache.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#452 Implement the fetch authorization information rest endpoint and model
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/applications.py
  hikari/guilds.py
  hikari/impl/bot.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/routes.py
  hikari/traits.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#460 Allow models to be used in cache calls in place of IDs.
  hikari/api/cache.py
  hikari/guilds.py
  hikari/impl/cache.py
  tests/hikari/impl/test_cache.py
Labels: enhancement

#462 Fix some issues in the documentation
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
Labels: devops, enhancement

#461 Remove partial implementation from GuildBuilder ABC
  hikari/api/special_endpoints.py
  hikari/impl/special_endpoints.py
Labels: enhancement

#459 More tests
  hikari/config.py
  hikari/events/message_events.py
  hikari/guilds.py
  hikari/impl/bot.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/collections.py
  hikari/internal/net.py
  hikari/internal/reflect.py
  hikari/internal/ux.py
  tests/hikari/events/test_member_events.py
  tests/hikari/events/test_message_events.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_shard.py
  tests/hikari/internal/test_collections.py
  tests/hikari/internal/test_routes.py
  tests/hikari/internal/test_ux.py
  tests/hikari/test_applications.py
  tests/hikari/test_config.py
  tests/hikari/test_event_stream.py
  tests/hikari/test_guilds.py
Labels: testing

#465 Remove member screening
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
Labels: a lost feature
