Repository hikari-py/hikari, pull requests merged in 2021-11, with the labels that each got.

#889 Allow for passing a URL for avatar_url on execute_webhook
  changes/889.feature.md
  hikari/api/rest.py
  hikari/impl/rest.py
  hikari/webhooks.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#885 Replace issue templates with issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: devops, skip-fragment-check

#890 Fix wrong indentation for render attribute
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: skip-fragment-check

#636 Start filtering events before unmarshalling
  hikari/api/cache.py
  hikari/api/entity_factory.py
  hikari/config.py
  hikari/events/base_events.py
  hikari/impl/bot.py
  hikari/impl/cache.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  hikari/impl/event_manager_base.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_event_manager_base.py
Labels: optimization

#897 Split bulk message delete and message delete into separate events
  changes/897.breaking.md
  changes/897.feature.md
  hikari/api/event_factory.py
  hikari/events/message_events.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  tests/hikari/events/test_message_events.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
Labels: enhancement, breaking

#864 Make EventStream a sync context manager + simplify filter behaviour
  changes/864.deprecation.md
  changes/864.feature.md
  hikari/api/event_manager.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  tests/hikari/impl/test_event_manager_base.py
Labels: enhancement, breaking

#906 Switch to more relaxed requirements
  changes/906.feature.md
  requirements.txt
  speedup-requirements.txt
Labels: devops

#911 Fix logic for asserting listeners to not error when using defaults for other arguments
  changes/911.bugfix.md
  hikari/impl/event_manager_base.py
Labels: bug

#914 Fix release workflow
  .github/workflows/ci.yml
  .github/workflows/prepare-release.yml
  scripts/deploy.sh
  scripts/prepare-release.sh
Labels: devops, skip-fragment-check

#919 EventStream is a context manager not menu (c-log)
  CHANGELOG.md
Labels: skip-fragment-check
