Repository hikari-py/hikari, pull requests merged in 2021-05, with the labels that each got.

#569 Document new REST error codes
  hikari/errors.py
Labels: documentation

#571 Add flag to disable collecting coverage
  .github/workflows/ci.yml
  pipelines/pytest.nox.py
Labels: devops

#575 Add guild.is_nsfw field
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/invites.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_guilds.py
Labels: enhancement

#574 Add missing empty slots to event stream interface
  hikari/event_stream.py
  tests/hikari/test_event_stream.py
Labels: bug

#573 Add expires_at field to Invite object + invite refactors
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/cache.py
  hikari/invites.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_invites.py
Labels: bug, enhancement

#562 On our way to 100% coverage
  hikari/embeds.py
  hikari/internal/collections.py
  hikari/internal/enums.py
  hikari/internal/spel.py
  tests/hikari/events/test_typing_events.py
  tests/hikari/impl/test_shard.py
  tests/hikari/internal/test_enums.py
  tests/hikari/test_snowflake.py
Labels: testing

#570 Implement adding and replacing attachments in message PATCH
  hikari/api/rest.py
  hikari/impl/rest.py
  hikari/messages.py
  hikari/webhooks.py
  tests/hikari/test_messages.py
  tests/hikari/test_webhooks.py
Labels: enhancement

#579 Combine coverage results and remove stackless support
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  README.md
  pipelines/docker/stackless-3.8.0b3/Dockerfile
  setup.py
Labels: a lost feature, devops

#583 Add tests for event unmarshalling
  hikari/api/event_factory.py
  hikari/events/channel_events.py
  hikari/events/member_events.py
  hikari/events/role_events.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
Labels: enhancement, testing

#584 Make some imports type checking only
  hikari/applications.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/embeds.py
  hikari/events/message_events.py
  hikari/events/typing_events.py
  hikari/guilds.py
  hikari/impl/cache.py
  hikari/internal/attr_extensions.py
  hikari/internal/net.py
  hikari/invites.py
  hikari/snowflakes.py
  hikari/users.py
  hikari/webhooks.py
Labels: enhancement

#572 Ensure Flags only handles int internally
  hikari/impl/entity_factory.py
  hikari/internal/enums.py
Labels: bug

#580 Handle InvalidStateError on waiter dispatch
  hikari/impl/event_manager_base.py
Labels: bug

#586 Update attrs to 21.2.0
  hikari/api/entity_factory.py
  hikari/api/event_manager.py
  hikari/applications.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/config.py
  hikari/embeds.py
  hikari/emojis.py
  hikari/errors.py
  hikari/events/base_events.py
  hikari/events/channel_events.py
  hikari/events/guild_events.py
  hikari/events/lifetime_events.py
  hikari/events/member_events.py
  hikari/events/message_events.py
  hikari/events/reaction_events.py
  hikari/events/role_events.py
  hikari/events/shard_events.py
  hikari/events/typing_events.py
  hikari/events/user_events.py
  hikari/events/voice_events.py
  hikari/files.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/cache.py
  hikari/internal/routes.py
  hikari/invites.py
  hikari/messages.py
  hikari/presences.py
  hikari/sessions.py
  hikari/templates.py
  hikari/users.py
  hikari/voices.py
  hikari/webhooks.py
  requirements.txt
  tests/hikari/events/test_base_events.py
  tests/hikari/internal/test_attr_extensions.py
  tests/hikari/internal/test_data_binding.py
Labels: dependencies, enhancement

#558 Improve request rate limiting
  hikari/impl/buckets.py
  hikari/impl/rate_limits.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/routes.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_rate_limits.py
  tests/hikari/impl/test_rest.py
Labels: bug, enhancement

#590 UnicodeEmoji should be hashable
  hikari/emojis.py
  hikari/messages.py
  hikari/presences.py
  hikari/users.py
Labels: bug, enhancement

#592 Add stage channel methods
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#598 Use `is` for object equity in tests
  tests/hikari/impl/test_rest.py
  tests/hikari/test_users.py
  tests/hikari/test_webhooks.py
Labels: testing

#588 Add tests for BotApp
  hikari/impl/bot.py
  hikari/impl/event_factory.py
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_bot.py
  tests/hikari/test_errors.py
Labels: testing

#599 Convert Message.link property to Message.make_link function
  hikari/messages.py
  tests/hikari/test_messages.py
Labels: bug

#604 Document new REST error codes and remove unnecessary ones
  hikari/__init__.py
  hikari/errors.py
  hikari/impl/event_factory.py
Labels: documentation

#605 Implement Team#name
  hikari/applications.py
  hikari/impl/entity_factory.py
  hikari/impl/special_endpoints.py
  hikari/iterators.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_applications.py
Labels: enhancement

#606 Let OwnGuildIterator rely on the default limit
  hikari/impl/special_endpoints.py
Labels: enhancement

#607 Add shard event payload dispatch
  hikari/api/event_factory.py
  hikari/events/shard_events.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager_base.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager_base.py
Labels: enhancement

#610 Remove git sha1 detection on HEAD
  dev-requirements.txt
  hikari/api/cache.py
  hikari/cli.py
  hikari/internal/ux.py
Labels: a lost feature

#609 Switch cache components configuration to flags
  hikari/config.py
  hikari/impl/cache.py
  tests/hikari/impl/test_cache.py
Labels: breaking, enhancement

#612 Fix parsing searching query to allow substring matching
  docs/css.mako
  docs/patched_pdoc.py
  docs/search.mako
  scripts/prebuild_index.js
Labels: bug

#616 Reset closing event on bot start
  hikari/impl/bot.py
Labels: bug

#615 Document DISCORD_CERTIFIED_MODERATOR
  hikari/users.py
Labels: enhancement

#618 Allow to not specify permissions in `create_role`
  hikari/impl/rest.py
Labels: bug

#622 Replace Guild.is_nsfw with Guild.nsfw_level
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/invites.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_guilds.py
Labels: breaking, enhancement

#628 ComponentNotRunningError error refactors
  hikari/errors.py
  hikari/impl/bot.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/special_endpoints.py
  hikari/traits.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/test_errors.py
Labels: breaking, enhancement
