Repository hikari-py/hikari, pull requests merged in 2021-07, with the labels that each got.

#689 Account for entries being ignored in audit log iter
  hikari/impl/special_endpoints.py
Labels: bug

#688 Split Webhook into type specific definitions
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/applications.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/events/channel_events.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/webhooks.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_channels.py
  tests/hikari/test_webhooks.py
Labels: breaking, enhancement

#631 Implement `target_application` and rename `target_user_type` to `target_type`
  hikari/api/rest.py
  hikari/applications.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/cache.py
  hikari/invites.py
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
Labels: breaking, enhancement

#591 Add guild methods
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/events/guild_events.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/presences.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_guilds.py
  tests/hikari/test_presences.py
Labels: enhancement

#629 Make voice and rest components multi-use
  hikari/api/rest.py
  hikari/api/voice.py
  hikari/impl/bot.py
  hikari/impl/event_manager.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/voice.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_voice.py
Labels: bug, documentation

#694 Some small cleanups
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  hikari/impl/bot.py
Labels: enhancement

#699 Fix Resourceish union by filling Resource generic value
  hikari/files.py
Labels: bug

#700 Account for more cases of not removing 0xfe0f in emoji.filename
  CONTRIBUTING.md
  README.md
  hikari/emojis.py
  pipelines/twemoji.nox.py
  scripts/test_twemoji_mapping.py
Labels: bug

#702 Actually start rest client in rest bot
  hikari/impl/rest_bot.py
  tests/hikari/impl/test_rest_bot.py
Labels: bug

#691 Add TextableGuildChannel mixin class + improve typing around guild text channel operations
  hikari/api/cache.py
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/applications.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/events/channel_events.py
  hikari/events/message_events.py
  hikari/events/typing_events.py
  hikari/guilds.py
  hikari/impl/cache.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/invites.py
  hikari/templates.py
  hikari/voices.py
  hikari/webhooks.py
  tests/hikari/test_channels.py
  tests/hikari/test_webhooks.py
Labels: breaking, bug, enhancement
