Repository hikari-py/hikari, pull requests merged in 2022-01, with the labels that each got.

#952 Fix docstrings for CommandOption.min|max_value
  hikari/commands.py
Labels: documentation, skip-fragment-check

#956 Bring back more concise typing for set_listener
  hikari/api/interaction_server.py
  hikari/impl/interaction_server.py
  hikari/impl/rest_bot.py
Labels: skip-fragment-check

#963 Fix handling of utf-8 audit log reasons
  changes/963.bugfix.md
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: bug

#972 Enable pytest-asyncio strict mode
  pyproject.toml
Labels: skip-fragment-check

#983 Bump multidict to ~=6.0
  requirements.txt
Labels: dependencies, python, skip-fragment-check

#982 Fix reset of attributes in UserImpl
  changes/982.bugfix.md
  hikari/users.py
Labels: bug

#924 Add context menu commands and autocomplete
  changes/924.feature.md
  hikari/api/entity_factory.py
  hikari/api/interaction_server.py
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/commands.py
  hikari/impl/entity_factory.py
  hikari/impl/interaction_server.py
  hikari/impl/rest.py
  hikari/impl/rest_bot.py
  hikari/impl/special_endpoints.py
  hikari/interactions/base_interactions.py
  hikari/interactions/command_interactions.py
  hikari/interactions/component_interactions.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/interactions/test_command_interactions.py
  tests/hikari/test_commands.py
Labels: enhancement

#971 Add ability to send attachments in an interaction initial response
  changes/971.feature.md
  hikari/api/rest.py
  hikari/impl/rest.py
  hikari/interactions/base_interactions.py
  tests/hikari/impl/test_rest.py
  tests/hikari/interactions/test_base_interactions.py
Labels: enhancement

#987 Remove pages and safety from the default nox sessions
  pipelines/nox.py
Labels: devops, skip-fragment-check

#988 Add some checks to the deploy and pre-release process to ensure correct behaviour
  scripts/deploy.sh
  scripts/prepare-release.sh
Labels: devops, skip-fragment-check

#961 Add URL methods and properties for rich presence assets.
  changes/961.feature.md
  hikari/impl/entity_factory.py
  hikari/internal/routes.py
  hikari/presences.py
  hikari/urls.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_presences.py
Labels: enhancement
