Repository hikari-py/hikari, pull requests merged in 2022-04, with the labels that each got.

#1120 Fix unicode decode error caused by `latin-1` encoding when sending the banner
  changes/1120.bugfix.md
  hikari/internal/ux.py
  tests/hikari/internal/test_ux.py
Labels: bug

#1125 Don't close low-level stdout stream when printing banner
  hikari/internal/ux.py
  tests/hikari/internal/test_ux.py
Labels: bug, skip-fragment-check

#1137 Fix docs examples for hikari.Permissions
  hikari/permissions.py
Labels: documentation, skip-fragment-check

#1128 Simplify logic for snowflake min and max
  hikari/snowflakes.py
  tests/hikari/test_snowflake.py
Labels: skip-fragment-check
