Repository hikari-py/hikari, pull requests merged in 2022-09, with the labels that each got.

#1281 Call a context menu command a context menu command not a slash command.
  hikari/commands.py
Labels: documentation, skip-fragment-check

#1284 Ignore GUILD_CREATE which contain unavailable guilds
  changes/1284.bugfix.md
  hikari/impl/event_manager.py
  tests/hikari/impl/test_event_manager.py
Labels: bug

#1273 Remove support for ProcessPoolExecutor executor when reading files
  changes/1273.breaking.md
  hikari/files.py
  pyproject.toml
  tests/hikari/test_files.py
Labels: enhancement, breaking

#1213 Improve BadRequestError error string
  changes/1213.bugfix.md
  hikari/errors.py
  tests/hikari/test_errors.py
Labels: enhancement

#847 Add 3.11-dev support
  .github/workflows/ci.yml
  README.md
  changes/847.feature.md
  hikari/impl/interaction_server.py
  setup.py
  speedup-requirements.txt
  tests/hikari/impl/test_interaction_server.py
Labels: devops

#1286 Turn warnings into errors in tests
  dev-requirements/flake8.txt
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/rest.py
  hikari/internal/deprecation.py
  hikari/messages.py
  pipelines/config.py
  pyproject.toml
  tests/hikari/__init__.py
  tests/hikari/events/test_guild_events.py
  tests/hikari/impl/test_rest.py
  tests/hikari/internal/test_deprecation.py
  tests/hikari/test_guilds.py
Labels: testing, skip-fragment-check

#1245 New gateway resume logic
  changes/1245.feature.md
  hikari/events/shard_events.py
  hikari/impl/event_factory.py
  hikari/impl/shard.py
  tests/hikari/events/test_shard_events.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_shard.py
Labels: enhancement

#1288 Temporarily disable testing in 3.11-dev due to CPython crash
  .github/workflows/ci.yml
Labels: skip-fragment-check

#1204 Improve components lifetime
  changes/1204.breaking.md
  changes/1204.bugfix.md
  changes/1204.feature.md
  hikari/api/event_manager.py
  hikari/api/shard.py
  hikari/impl/bot.py
  hikari/impl/buckets.py
  hikari/impl/config.py
  hikari/impl/event_manager_base.py
  hikari/impl/interaction_server.py
  hikari/impl/rest_bot.py
  hikari/impl/shard.py
  hikari/internal/aio.py
  hikari/internal/net.py
  hikari/internal/signals.py
  hikari/traits.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_interaction_server.py
  tests/hikari/impl/test_rest_bot.py
  tests/hikari/impl/test_shard.py
  tests/hikari/internal/test_signals.py
Labels: enhancement, optimization

#1290 Fix towncrier installation
  changes/1204.breaking.md
  changes/1204.feature.md
  scripts/prepare-release.sh
Labels: skip-fragment-check
