Repository hikari-py/hikari, pull requests merged in 2022-02, with the labels that each got.

#995 Fix `$browser` to use the correct format
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: skip-fragment-check

#996 Improve deprecation notices for rest cmd methods
  hikari/api/rest.py
  hikari/impl/rest.py
Labels: skip-fragment-check

#986 Merge ed25519 dependencies to an optional server feature flag
  .github/workflows/ci.yml
  README.md
  changes/986.breaking.md
  hikari/impl/interaction_server.py
  hikari/internal/ed25519.py
  pipelines/mypy.nox.py
  pipelines/pytest.nox.py
  requirements.txt
  server-requirements.txt
  setup.py
  speedup-requirements.txt
  tests/hikari/impl/test_interaction_server.py
  tests/hikari/impl/test_rest_bot.py
  tests/hikari/internal/test_ed25519.py
Labels: breaking

#993 Fix changelog fragment inconsistencies + add deprecation changelog fragment for 924
  changes/924.deprecation.md
  changes/924.feature.md
  changes/954.bugfix.md
  changes/955.feature.md
  changes/957.feature.md
  changes/959.feature.md
  changes/962.feature.md
  changes/971.feature.md
  changes/975.feature.md
  changes/984.feature.md
Labels: skip-fragment-check

#1000 Remove requirements files from the manifest
  MANIFEST.in
Labels: skip-fragment-check

#1001 Fix coverage collection
  pipelines/pytest.nox.py
  pyproject.toml
Labels: devops, skip-fragment-check

#998 Improve the semantics of enable_signal_handlers
  changes/998.bugfix.md
  hikari/impl/bot.py
  hikari/impl/interaction_server.py
  hikari/impl/rest_bot.py
  tests/hikari/impl/test_interaction_server.py
Labels: enhancement

#1005 Optimize tests and fix flaky tests to reduce race conditions
  hikari/internal/collections.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_rate_limits.py
  tests/hikari/impl/test_rest.py
  tests/hikari/internal/test_aio.py
  tests/hikari/internal/test_collections.py
Labels: optimization, testing, skip-fragment-check

#1012 Fix nested autocomplete option handling in interactions
  changes/1012.bugfix.md
  hikari/impl/entity_factory.py
  hikari/interactions/command_interactions.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug

#1013 Remove redundant CommandBuilder fields
  hikari/api/special_endpoints.py
  hikari/impl/special_endpoints.py
Labels: skip-fragment-check

#1018 Fix deploy for the last time ever
  scripts/deploy.sh
  scripts/prepare-release.sh
Labels: skip-fragment-check

#1019 Improve examples folder layout and cleanup rillrate example
  examples/LICENSE
  examples/__init__.py
  examples/hello_world.py
  examples/hello_world/__init__.py
  examples/hello_world/hello_world.bat
  examples/hello_world/hello_world.py
  examples/hello_world/hello_world.sh
  examples/image_resources.py
  examples/image_resources/__init__.py
  examples/image_resources/image_resources.bat
  examples/image_resources/image_resources.sh
  examples/simple_dashboard.py
  examples/simple_dashboard/__init__.py
  examples/simple_dashboard/requirements.txt
  examples/simple_dashboard/simple_dashboard.bat
  examples/simple_dashboard/simple_dashboard.py
  examples/simple_dashboard/simple_dashboard.sh
  examples/simple_dashboard_requirements.txt
Labels: documentation, skip-fragment-check

#1014 Attempt to reconnect on a gateway TimeoutError
  changes/1014.bugfix.md
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: bug

#1026 Rename covariant `T` to `T_co`.
  hikari/internal/data_binding.py
Labels: skip-fragment-check

#1028 Fix various spelling mistakes
  .github/workflows/ci.yml
  .github/workflows/prepare-release.yml
  CHANGELOG.md
  hikari/api/interaction_server.py
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/bot.py
  hikari/impl/event_manager_base.py
  hikari/impl/interaction_server.py
  hikari/impl/rate_limits.py
  hikari/impl/rest_bot.py
  hikari/internal/enums.py
  hikari/internal/time.py
  hikari/presences.py
  hikari/snowflakes.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/test_guilds.py
Labels: skip-fragment-check
