Repository hikari-py/hikari, pull requests merged in 2022-11, with the labels that each got.

#1334 Add hikari.Permissions.MANAGE_EVENT
  changes/1334.feature.md
  hikari/permissions.py
  tests/hikari/test_permissions.py
Labels: enhancement

#1330 Support specifying `with_counts` and `with_expiration` in `RESTClient.fetch_invite`
  changes/1330.doc.md
  hikari/api/rest.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#1337 Catch UnrecognisedEntityErrors in rest list methods
  changes/1337.bugfix.md
  hikari/api/entity_factory.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/data_binding.py
  tests/hikari/impl/test_rest.py
Labels: bug

#1344 Fix deprecation warnings in cpython3.11
  changes/1344.bugfix.md
  hikari/internal/ux.py
  tests/hikari/internal/test_ux.py
Labels: bug

#1347 Remove previously deprecated functionality
  changes/1347.breaking.md
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/cache.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/internal/test_cache.py
  tests/hikari/test_guilds.py
  tests/hikari/test_messages.py
Labels: breaking

#1348 chore: update Discord API version in README
  README.md
  hikari/api/shard.py
  hikari/impl/rest.py
  hikari/impl/shard.py
Labels: skip-fragment-check

#1356 Split linting commands
  .github/workflows/ci.yml
Labels: devops, skip-fragment-check

#1358 Fix readme ver list
  README.md
Labels: skip-fragment-check

#1366 Expose shard impl
  hikari/impl/__init__.py
  hikari/impl/__init__.pyi
  hikari/impl/shard.py
Labels: skip-fragment-check

#1367 Only use attachment upload method when editing messages
  changes/1367.bugfix.md
  hikari/impl/rest.py
  hikari/messages.py
  tests/hikari/impl/test_rest.py
Labels: bug

#1369 Improve voice listener
  changes/1369.bugfix.md
  changes/1369.feature.md
  hikari/impl/bot.py
  hikari/impl/voice.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_voice.py
Labels: bug, enhancement

#1368 Allow specifying a filename to URL
  changes/1368.feature.md
  hikari/files.py
  tests/hikari/test_files.py
Labels: enhancement
