Repository hikari-py/hikari, pull requests merged in 2022-03, with the labels that each got.

#1040 Some small doc fixes
  hikari/api/rest.py
  hikari/audit_logs.py
  hikari/impl/bot.py
Labels: skip-fragment-check

#1024 Add a slash command example
  examples/slash.py
Labels: skip-fragment-check

#1044 Remove unnecessary pyright version lock
  hikari/channels.py
  pipelines/config.py
  pipelines/pyright.nox.py
Labels: devops, skip-fragment-check

#841 Fix bucket lock not being released on errors while being acquired
  changes/841.bugfix.md
  hikari/impl/buckets.py
  hikari/impl/rate_limits.py
  hikari/impl/rest.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_rate_limits.py
Labels: bug

#796 Feature: Embed total_length() function
  changes/796.feature.md
  hikari/embeds.py
  tests/hikari/test_embeds.py
Labels: enhancement

#1052 Changelog typo fix
  changes/1041.feature.md
Labels: skip-fragment-check

#1023 Properly close when not fully started
  changes/1023.bugfix.md
  hikari/api/shard.py
  hikari/impl/bot.py
  hikari/impl/shard.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_voice.py
Labels: enhancement

#1058 Optimize 'receive_json' for the happy path
  changes/1058.feature.md
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: optimization

#1059 Fix fetch own guilds when newest_first is True
  changes/1059.bugfix.md
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_special_endpoints.py
Labels: bug

#1056 Guild Scheduled events
  changes/1056.feature.md
  hikari/__init__.py
  hikari/__init__.pyi
  hikari/api/entity_factory.py
  hikari/api/event_factory.py
  hikari/api/rest.py
  hikari/events/__init__.py
  hikari/events/__init__.pyi
  hikari/events/scheduled_events.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/intents.py
  hikari/internal/data_binding.py
  hikari/internal/routes.py
  hikari/scheduled_events.py
  tests/hikari/events/test_scheduled_events.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/internal/test_data_binding.py
  tests/hikari/test_scheduled_events.py
Labels: enhancement

#1063 Require pytest-asyncio to run pytest
  pyproject.toml
Labels: devops, skip-fragment-check

#1061 Fix handling of when the first zlib message is complete
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: bug, skip-fragment-check

#1071 Speedup tests by mocking sleep calls
  tests/hikari/internal/test_ux.py
Labels: testing, skip-fragment-check

#1075 Remove nonce parameter from create message
  changes/1075.breaking.md
  hikari/api/rest.py
  hikari/channels.py
  hikari/impl/rest.py
  hikari/messages.py
  hikari/users.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_channels.py
  tests/hikari/test_messages.py
  tests/hikari/test_users.py
Labels: breaking

#1067 Split config module between api.config and impl.config
  changes/1067.breaking.md
  hikari/__init__.py
  hikari/__init__.pyi
  hikari/api/__init__.py
  hikari/api/__init__.pyi
  hikari/api/config.py
  hikari/impl/__init__.py
  hikari/impl/__init__.pyi
  hikari/impl/bot.py
  hikari/impl/cache.py
  hikari/impl/config.py
  hikari/impl/rest.py
  hikari/impl/rest_bot.py
  hikari/impl/shard.py
  hikari/internal/net.py
  hikari/internal/ux.py
  hikari/traits.py
  pipelines/pyright.nox.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_config.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_rest_bot.py
  tests/hikari/impl/test_shard.py
  tests/hikari/internal/test_ux.py
Labels: breaking

#1089 fix GuildFeature.MORE_STICKERS
  changes/1989.bugfix.md
  hikari/guilds.py
Labels: bug

#1090 add hikari.locales.Locale
  changes/1990.feature.md
  hikari/__init__.py
  hikari/__init__.pyi
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/interactions/command_interactions.py
  hikari/interactions/component_interactions.py
  hikari/locales.py
  hikari/templates.py
  hikari/users.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#1086 Remove `VoiceRegion.is_vip` due to Discord no longer sending it
  changes/1086.breaking.md
  hikari/api/rest.py
  hikari/impl/entity_factory.py
  hikari/voices.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug, breaking

#1098 Temporarily freeze jinja2 to 3.0.3
  flake8-requirements.txt
Labels: skip-fragment-check

#1101 Fix locale bugs and regressions
  hikari/impl/entity_factory.py
  hikari/interactions/command_interactions.py
  hikari/users.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug, skip-fragment-check

#1069 Disable ws autoclose
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: skip-fragment-check

#1105 Remove redundant event factory assertions
  hikari/impl/event_factory.py
Labels: skip-fragment-check

#1107 Fix incorrect changelog PR link
  CHANGELOG.md
Labels: skip-fragment-check

#1109 Remove functions exported in top level package
  hikari/__init__.py
  hikari/__init__.pyi
Labels: skip-fragment-check

#1114 Bump black to 22.3.0
  dev-requirements.txt
Labels: dependencies, python, skip-fragment-check
