Repository hikari-py/hikari, pull requests merged in 2022-06, with the labels that each got.

#1149 Merge mention object into message object
  changes/1149.deprecation.md
  hikari/impl/cache.py
  hikari/impl/entity_factory.py
  hikari/internal/cache.py
  hikari/messages.py
  tests/hikari/impl/test_cache.py
  tests/hikari/test_messages.py
Labels: enhancement

#1180 Add hikari-crescent to command handlers in README
  README.md
Labels: skip-fragment-check

#1190 Remove dollar sign from identify payload
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: enhancement, skip-fragment-check

#1192 Keep message reference when updating cache messages
  changes/1192.bugfix.md
  hikari/impl/cache.py
  hikari/impl/entity_factory.py
  hikari/internal/cache.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug

#1202 Improve ci-done workflow
  .github/workflows/ci.yml
Labels: devops, skip-fragment-check
