Repository hikari-py/hikari, pull requests merged in 2022-12, with the labels that each got.

#1382 Add new nsfw field for commands
  changes/1382.feature.md
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/commands.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/test_commands.py
Labels: enhancement

#1385 Add plugin to verify noqa comments
  dev-requirements/flake8.txt
  hikari/api/cache.py
  hikari/api/interaction_server.py
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/channels.py
  hikari/colors.py
  hikari/impl/entity_factory.py
  hikari/impl/rate_limits.py
  hikari/impl/special_endpoints.py
  hikari/internal/aio.py
  hikari/internal/data_binding.py
  hikari/users.py
  hikari/webhooks.py
  tests/hikari/impl/test_rest.py
  tests/hikari/internal/test_signals.py
Labels: devops, skip-fragment-check

#1386 Remove incorrect `is_nsfw` from threads
  changes/1386.bugfix.md
  hikari/channels.py
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_channels.py
Labels: bug

#1384 Threads cache
  changes/1384.feature.md
  hikari/api/cache.py
  hikari/api/config.py
  hikari/impl/cache.py
  hikari/impl/event_manager.py
  hikari/internal/cache.py
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_event_manager.py
Labels: enhancement

#1388 Fix empty SHA in release webhook
  scripts/release.sh
Labels: devops, skip-fragment-check

#1390 Fix error in logs due to missing replacement variable
  hikari/impl/shard.py
Labels: bug, skip-fragment-check

#1389 Remove left-over `builtins.` from docs
  hikari/api/cache.py
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/files.py
  hikari/interactions/base_interactions.py
  hikari/interactions/modal_interactions.py
  hikari/internal/cache.py
Labels: documentation, skip-fragment-check

#1397 Fix grammar
  hikari/interactions/base_interactions.py
Labels: documentation, skip-fragment-check

#1404 locale: add indonesian
  changes/1404.feature.md
  hikari/locales.py
Labels: enhancement

#1391 Implement some documentation feedback and fixes
  docs/_static/extra.css
  docs/_templates/python/data.rst
  docs/_templates/python/module.rst
  hikari/api/rest.py
  hikari/audit_logs.py
  hikari/components.py
  hikari/guilds.py
  hikari/interactions/base_interactions.py
  hikari/interactions/modal_interactions.py
  pipelines/sphinx.nox.py
Labels: documentation, skip-fragment-check

#1412 Improve pyright compatibility
  changes/1412.feature.md
  hikari/embeds.py
  hikari/files.py
  hikari/impl/entity_factory.py
  hikari/impl/special_endpoints.py
  hikari/internal/enums.pyi
  hikari/internal/ux.py
  hikari/presences.py
  tests/hikari/events/test_base_events.py
  tests/hikari/internal/test_attr_extensions.py
Labels: enhancement

#1409 Fix "." rendering in the docs
  hikari/api/event_manager.py
  hikari/files.py
  hikari/internal/spel.py
  hikari/iterators.py
Labels: documentation, skip-fragment-check
