Repository hikari-py/hikari, pull requests merged in 2022-08, with the labels that each got.

#1238 Move dev dependencies to smaller files
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/fragments-check.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  dev-requirements.txt
  dev-requirements/build.txt
  dev-requirements/codespell.txt
  dev-requirements/coverage.txt
  dev-requirements/flake8.txt
  dev-requirements/formatting.txt
  dev-requirements/mypy.txt
  dev-requirements/nox.txt
  dev-requirements/pdoc.txt
  dev-requirements/pyright.txt
  dev-requirements/pytest.txt
  dev-requirements/release.txt
  dev-requirements/safety.txt
  dev-requirements/slotscheck.txt
  dev-requirements/towncrier.txt
  dev-requirements/twemoji.txt
  pipelines/codespell.nox.py
  pipelines/config.py
  pipelines/flake8.nox.py
  pipelines/format.nox.py
  pipelines/mypy.nox.py
  pipelines/nox.py
  pipelines/pages.nox.py
  pipelines/pyright.nox.py
  pipelines/pytest.nox.py
  pipelines/safety.nox.py
  pipelines/slotscheck.nox.py
  pipelines/twemoji.nox.py
  scripts/deploy.sh
  scripts/prepare-release.sh
Labels: devops, skip-fragment-check

#1242 Fix voice silently failing to connect to channel
  changes/1242.bugfix.md
  hikari/api/voice.py
  hikari/impl/voice.py
  tests/hikari/impl/test_voice.py
Labels: bug

#1253 Remove redundant dependabot target
  .github/dependabot.yml
Labels: devops, skip-fragment-check

#1247 More precise snowflake datetime conversion
  changes/1247.bugfix.md
  hikari/internal/time.py
  tests/hikari/internal/test_time.py
Labels: bug

#1254 docs: fix intellisense relation for `DeferredResponseTypesT`
  hikari/interactions/base_interactions.py
Labels: skip-fragment-check

#1259 Fix endpoint used in reposition_channels
  changes/1259.bugfix.md
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: bug

#1141 Application Command Localizations
  changes/1141.feature.md
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/commands.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
Labels: enhancement

#1263 Fix PermissionOverwrite Example
  hikari/channels.py
Labels: documentation, skip-fragment-check

#1264 Fix incorrect deprecation version for `RESTClientImpl.edit_permission_overwrites`
  hikari/impl/rest.py
Labels: skip-fragment-check

#1269 Expose __git_sha1__ (and other fields) top level
  hikari/__init__.py
  hikari/__init__.pyi
Labels: skip-fragment-check

#1270 Remove codespell from reformat-code
  pipelines/format.nox.py
Labels: devops, skip-fragment-check

#1274 Include name_localizations on MenuBuilder.create
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_special_endpoints.py
Labels: bug, skip-fragment-check
