Repository hikari-py/hikari, pull requests merged in 2022-10, with the labels that each got.

#1307 fix: wrong type in InviteGuild.features
  changes/1307.bugfix.md
  hikari/invites.py
Labels: bug

#1294 Remove un-used test code
  hikari/impl/rest.py
  tests/hikari/client_session_stub.py
  tests/hikari/hikari_test_helpers.py
Labels: testing, skip-fragment-check

#1293 Allow to change shard trace level on the fly
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: skip-fragment-check

#1318 Fix docstrings
  hikari/api/rest.py
  hikari/api/special_endpoints.py
Labels: skip-fragment-check

#1321 Bundle requirement files with source distribution
  MANIFEST.in
Labels: skip-fragment-check

#999 Add startup and shutdown callbacks to the RESTBot interface
  changes/999.feature.md
  hikari/impl/rest_bot.py
  hikari/traits.py
  tests/hikari/impl/test_rest_bot.py
Labels: enhancement

#811 Threads
  README.md
  changes/811.breaking.md
  changes/811.feature.md
  hikari/api/cache.py
  hikari/api/entity_factory.py
  hikari/api/event_factory.py
  hikari/api/rest.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/events/channel_events.py
  hikari/events/guild_events.py
  hikari/guilds.py
  hikari/impl/cache.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  hikari/impl/event_manager_base.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/special_endpoints.py
  hikari/intents.py
  hikari/interactions/command_interactions.py
  hikari/interactions/component_interactions.py
  hikari/internal/cache.py
  hikari/internal/routes.py
  hikari/messages.py
  hikari/urls.py
  tests/hikari/events/test_channel_events.py
  tests/hikari/events/test_guild_events.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/interactions/test_command_interactions.py
  tests/hikari/interactions/test_component_interactions.py
  tests/hikari/test_audit_logs.py
  tests/hikari/test_channels.py
Labels: enhancement, breaking

#1324 Enable testing in CPython 3.11
  .github/workflows/ci.yml
  README.md
Labels: devops, skip-fragment-check

#1260 Support v10 attachments edits
  changes/1260.breaking.md
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/channels.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/impl/special_endpoints.py
  hikari/interactions/base_interactions.py
  hikari/messages.py
  hikari/urls.py
  hikari/users.py
  hikari/webhooks.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/interactions/test_base_interactions.py
  tests/hikari/test_messages.py
  tests/hikari/test_webhooks.py
Labels: enhancement, breaking

#1332 Add .gitattributes file
  hikari/impl/.gitattributes
Labels: skip-fragment-check

#1333 Fix raise_interrupt test failing on some platforms
  tests/hikari/internal/test_signals.py
Labels: skip-fragment-check

#1336 Move .gitattributes top level
  .gitattributes
  hikari/impl/.gitattributes
Labels: skip-fragment-check
