Repository hikari-py/hikari, pull requests merged in 2023-03, with the labels that each got.

#1530 Correct seconds to minutes in docs for auto_archive_duration
  hikari/api/rest.py
  hikari/channels.py
  hikari/guilds.py
Labels: documentation, skip-fragment-check

#1529 Await bucket manager gc task to completion when closing
  changes/1529.bugfix.md
  hikari/impl/buckets.py
  hikari/impl/rest.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_rest.py
Labels: bug

#1531 Go back to PyPI release of myst-parser
  dev-requirements/sphinx.txt
  docs/_templates/python/data.rst
  docs/_templates/python/module.rst
Labels: documentation, skip-fragment-check

#1504 Add suppress_notifications bit flag to MessageFlag
  changes/1504.feature.md
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/interactions/base_interactions.py
  hikari/messages.py
  hikari/webhooks.py
Labels: enhancement

#1532 Add flag to skip generation of reference docs when running sphinx
  README.md
  docs/conf.py
  hikari/api/rest.py
  pipelines/sphinx.nox.py
Labels: documentation, skip-fragment-check

#1535 Remove deprecated behaviour for 2.0.0.dev118
  changes/1535.breaking.md
  hikari/api/special_endpoints.py
  hikari/components.py
  hikari/impl/special_endpoints.py
  hikari/intents.py
  tests/hikari/impl/test_special_endpoints.py
Labels: breaking

#1545 Read the banner with `utf-8` encoding
  changes/1545.bugfix.md
  hikari/internal/ux.py
  tests/hikari/internal/test_ux.py
Labels: bug

#1553 General repository cleanup
  .gitattributes
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  README.md
  dev-requirements.txt
  pipelines/codespell.nox.py
  pipelines/flake8.nox.py
  pipelines/format.nox.py
  pipelines/mypy.nox.py
  pipelines/nox.py
  pipelines/pyright.nox.py
  pipelines/pytest.nox.py
  pipelines/safety.nox.py
  pipelines/slotscheck.nox.py
  pipelines/sphinx.nox.py
  pipelines/twemoji.nox.py
  pipelines/utils.nox.py
  scripts/benchmarks/enum_benchmark.py
  scripts/benchmarks/flag_benchmark.py
  scripts/benchmarks/protocol_benchmark.py
  scripts/ci/increase_version_number.py
  scripts/ci/normalize_coverage.py
  scripts/ci/prepare-release.sh
  scripts/ci/release-manually.sh
  scripts/ci/release.sh
  scripts/ci/test_twemoji_mapping.py
  scripts/release-webhook.sh
Labels: devops, skip-fragment-check

#1549 Improve bucket ratelimiting logging
  hikari/impl/rate_limits.py
  tests/hikari/impl/test_rate_limits.py
Labels: enhancement, skip-fragment-check

#1561 Remove fragments check concurrency check
  .github/workflows/fragments-check.yml
Labels: devops, skip-fragment-check

#1560 Add in missed field aliases for imessagebuilder mention fields
  changes/1560.bugfix.md
  hikari/impl/special_endpoints.py
Labels: bug

#1528 Return @everyone for the everyone role's mention
  changes/1528.feature.md
  hikari/guilds.py
  tests/hikari/test_guilds.py
Labels: enhancement

#1533 Flatten the component builders
  changes/1533.breaking.md
  changes/1533.bugfix.md
  changes/1533.deprecation.md
  changes/1533.feature.md
  hikari/api/special_endpoints.py
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
Labels: enhancement

#1564 Fix forum applied tags
  changes/1564.bugfix.md
  hikari/api/rest.py
  hikari/channels.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: bug
