Repository hikari-py/hikari, pull requests merged in 2023-02, with the labels that each got.

#1472 Fix RESTApp example and add RESTBot example
  README.md
  tests/hikari/internal/test_ux.py
Labels: documentation, skip-fragment-check

#1473 Add utilities to aid with enum member deprecation
  hikari/internal/deprecation.py
  hikari/internal/enums.py
  hikari/internal/enums.pyi
  tests/hikari/internal/test_enums.py
Labels: skip-fragment-check

#1480 Fix `ChannelFollowWebhook` not including source in all cases
  changes/1480.bugfix.md
  hikari/impl/entity_factory.py
  hikari/webhooks.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug

#1485 Improve logging consistency and add support for `.ini` files
  changes/1485.breaking.md
  changes/1485.bugfix.md
  changes/1485.feature.md
  hikari/impl/bot.py
  hikari/impl/rest_bot.py
  hikari/internal/ux.py
  tests/hikari/internal/test_ux.py
Labels: bug, enhancement, breaking

#1471 Add support for audit log entry events
  changes/1471.deprecation.md
  changes/1471.feature.md
  hikari/api/entity_factory.py
  hikari/api/event_factory.py
  hikari/audit_logs.py
  hikari/events/guild_events.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  hikari/impl/special_endpoints.py
  hikari/intents.py
  hikari/internal/enums.py
  tests/hikari/events/test_guild_events.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/test_audit_logs.py
  tests/hikari/test_errors.py
Labels: enhancement

#1486 Add `orjson` as an optional speedup and allow to pass custom `json.dumps` and `json.loads` functions to all components.
  README.md
  changes/1486.feature.md
  hikari/errors.py
  hikari/impl/bot.py
  hikari/impl/interaction_server.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/internal/data_binding.py
  hikari/internal/net.py
  hikari/internal/time.py
  hikari/internal/ux.py
  speedup-requirements.txt
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_interaction_server.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
  tests/hikari/internal/test_data_binding.py
  tests/hikari/internal/test_net.py
  tests/hikari/internal/test_time.py
  tests/hikari/internal/test_ux.py
  tests/hikari/test_errors.py
Labels: enhancement

#1441 Remove `RateLimitedError` and make the global ratelimit abide by `max_rate_limit`
  changes/1441.breaking.md
  changes/1441.bugfix.md
  hikari/api/rest.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/commands.py
  hikari/errors.py
  hikari/events/channel_events.py
  hikari/events/typing_events.py
  hikari/guilds.py
  hikari/impl/buckets.py
  hikari/impl/rate_limits.py
  hikari/impl/rest.py
  hikari/interactions/base_interactions.py
  hikari/interactions/command_interactions.py
  hikari/interactions/component_interactions.py
  hikari/interactions/modal_interactions.py
  hikari/internal/routes.py
  hikari/internal/time.py
  hikari/messages.py
  hikari/presences.py
  hikari/users.py
  hikari/webhooks.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_rest.py
  tests/hikari/internal/test_routes.py
  tests/hikari/test_errors.py
Labels: bug, breaking

#1422 Add linked roles support
  changes/1422.feature.md
  hikari/__init__.py
  hikari/__init__.pyi
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/applications.py
  hikari/commands.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/routes.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#1493 Fix `URLEncodedFormBuilder` treating fields as files
  hikari/impl/rest.py
  hikari/internal/data_binding.py
  tests/hikari/impl/test_rest.py
  tests/hikari/internal/test_data_binding.py
Labels: bug, skip-fragment-check

#1494 Remove newer references to RateLimitedError
  hikari/api/rest.py
  hikari/templates.py
Labels: skip-fragment-check

#1423 Pre-maturely fetch the public key if not present when starting an interaction server
  changes/1423.feature.md
  hikari/impl/interaction_server.py
  tests/hikari/impl/test_interaction_server.py
Labels: enhancement

#1496 Remove previously deprecated functionality with scheduled removal in 2.0.0.dev117
  changes/1496.breaking.md
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_guilds.py
Labels: breaking

#1500 Switch `sphinx-autoapi` back to PyPI release
  dev-requirements/sphinx.txt
Labels: devops, skip-fragment-check

#1503 Enable merge queues
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: devops, skip-fragment-check

#1510 Remove `merge_group` trigger
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: devops, skip-fragment-check

#1513 Remove unused imports in test_event_manager_base.py
  tests/hikari/impl/test_event_manager_base.py
Labels: skip-fragment-check
