Repository hikari-py/hikari, pull requests merged in 2023-11, with the labels that each got.

#1744 Improved shard connect and shard disconnect to reliably call the event on time
  changes/1744.bugfix.md
  hikari/events/shard_events.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  tests/hikari/impl/test_shard.py
Labels: bug

#1740 Add missing clear methods for InteractionMessageBuilder
  changes/1740.feature.md
  hikari/api/special_endpoints.py
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_special_endpoints.py
Labels: enhancement

#1745 Improve force exiting (double interrupt)
  changes/1745.bugfix.md
  hikari/errors.py
  hikari/impl/gateway_bot.py
  hikari/impl/rest_bot.py
  hikari/internal/aio.py
  hikari/internal/signals.py
  tests/hikari/internal/test_signals.py
Labels: bug

#1357 Add Python 3.12 support
  .github/workflows/ci.yml
  README.md
  changes/1357.feature.md
  hikari/impl/shard.py
  hikari/internal/fast_protocol.py
  requirements.txt
  setup.py
  tests/hikari/impl/test_event_manager_base.py
Labels: devops

#1758 Add missing permissions
  changes/1758.deprecation.md
  changes/1758.feature.md
  hikari/internal/enums.py
  hikari/permissions.py
  tests/hikari/test_permissions.py
Labels: enhancement

#1760 Fix towncrier not adding a newline at the end
  changes/.template.rst
Labels: devops, skip-fragment-check

#1763 Rename incorrect readthedocs config extension
  .readthedocs.yaml
Labels: skip-fragment-check
