Repository hikari-py/hikari, pull requests merged in 2023-07, with the labels that each got.

#1648 Retry REST requests on connection errors
  changes/1648.bugfix.md
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: bug

#1645 Handle connection reset error
  changes/1645.bugfix.md
  hikari/impl/shard.py
Labels: bug

#1667 Add code block in `hikari.embeds`'s docs
  hikari/embeds.py
Labels: documentation, skip-fragment-check

#1663 Automatically rename changelog fragments that start with idk
  .github/workflows/fragments-check.yml
Labels: devops, skip-fragment-check

#1674 Remove renaming "idk" changelog files
  .github/workflows/fragments-check.yml
Labels: devops, skip-fragment-check
