Repository hikari-py/hikari, pull requests merged in 2023-08, with the labels that each got.

#1673 Fix incorrect calculation for the default avatar of migrated users
  changes/1673.bugfix.md
  hikari/internal/routes.py
  hikari/users.py
  hikari/webhooks.py
  tests/hikari/test_users.py
Labels: bug

#1659 Add with_counts information for OwnGuilds
  changes/1659.feature.md
  hikari/applications.py
  hikari/impl/entity_factory.py
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_special_endpoints.py
Labels: enhancement

#1682 Fix the uses of `deprecated` directive and fix deadlinks to `GatewayBot`
  README.md
  hikari/__init__.py
  hikari/impl/gateway_bot.py
  hikari/users.py
Labels: documentation, skip-fragment-check

#1679 feat: add CacheSettings.only_my_member
  changes/1679.feature.md
  hikari/api/config.py
  hikari/impl/config.py
  hikari/impl/event_manager.py
  hikari/impl/gateway_bot.py
  tests/hikari/impl/test_event_manager.py
Labels: enhancement
