Repository hikari-py/hikari, pull requests merged in 2023-04, with the labels that each got.

#1539 name_localization field to command choice + some deprecations
  changes/1539.deprecation.md
  changes/1539.feature.md
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/commands.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/aio.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
Labels: enhancement

#1573 Support Autocomplete response builder for interaction methods
  hikari/api/rest.py
  hikari/impl/rest.py
  hikari/interactions/command_interactions.py
  tests/hikari/interactions/test_command_interactions.py
Labels: skip-fragment-check

#1572 Fix sticker pack handling and typing
  changes/1572.breaking.md
  changes/1572.bugfix.md
  hikari/impl/entity_factory.py
  hikari/stickers.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_stickers.py
Labels: bug

#1571 Add support for sending sticker_ids on create_message
  changes/1571.feature.md
  hikari/api/rest.py
  hikari/channels.py
  hikari/impl/rest.py
  hikari/messages.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_channels.py
  tests/hikari/test_messages.py
Labels: enhancement

#1550 Implement guild role subscriptions
  changes/1550.feature.md
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_guilds.py
Labels: enhancement

#1569 Revert changing the default nox -s ordering
  pipelines/codespell.nox.py
  pipelines/flake8.nox.py
  pipelines/format.nox.py
  pipelines/mypy.nox.py
  pipelines/nox.py
  pipelines/pyright.nox.py
  pipelines/pytest.nox.py
  pipelines/safety.nox.py
  pipelines/slotscheck.nox.py
Labels: devops, skip-fragment-check

#1575 Switch to importing from attrs
  hikari/api/event_manager.py
  hikari/applications.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/commands.py
  hikari/components.py
  hikari/embeds.py
  hikari/emojis.py
  hikari/errors.py
  hikari/events/application_events.py
  hikari/events/base_events.py
  hikari/events/channel_events.py
  hikari/events/guild_events.py
  hikari/events/interaction_events.py
  hikari/events/lifetime_events.py
  hikari/events/member_events.py
  hikari/events/message_events.py
  hikari/events/reaction_events.py
  hikari/events/role_events.py
  hikari/events/scheduled_events.py
  hikari/events/shard_events.py
  hikari/events/typing_events.py
  hikari/events/user_events.py
  hikari/events/voice_events.py
  hikari/files.py
  hikari/guilds.py
  hikari/impl/bot.py
  hikari/impl/config.py
  hikari/impl/entity_factory.py
  hikari/impl/event_manager_base.py
  hikari/impl/special_endpoints.py
  hikari/interactions/base_interactions.py
  hikari/interactions/command_interactions.py
  hikari/interactions/component_interactions.py
  hikari/interactions/modal_interactions.py
  hikari/internal/aio.py
  hikari/internal/attrs_extensions.py
  hikari/internal/cache.py
  hikari/internal/routes.py
  hikari/invites.py
  hikari/messages.py
  hikari/presences.py
  hikari/scheduled_events.py
  hikari/sessions.py
  hikari/stickers.py
  hikari/templates.py
  hikari/users.py
  hikari/voices.py
  hikari/webhooks.py
  tests/hikari/events/test_base_events.py
  tests/hikari/internal/test_attr_extensions.py
  tests/hikari/internal/test_data_binding.py
Labels: skip-fragment-check

#1578 Remove left-over pdoc requirements
  dev-requirements/pdoc.txt
Labels: skip-fragment-check

#1576 Move `hikari.impl.bot` to `hikari.impl.gateway_bot`
  changes/1576.deprecation.md
  hikari/impl/__init__.py
  hikari/impl/__init__.pyi
  hikari/impl/bot.py
  hikari/impl/gateway_bot.py
  tests/hikari/impl/test_gateway_bot.py
  tests/hikari/test_guilds.py
  tests/hikari/test_presences.py
  tests/hikari/test_snowflake.py
Labels: enhancement

#1580 Remove deprecated functionality for 2.0.0.dev119
  changes/1580.breaking.md
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/interactions/command_interactions.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/interactions/test_command_interactions.py
Labels: breaking

#1595 Update warning for optimization level 0
  hikari/internal/ux.py
Labels: enhancement, skip-fragment-check

#1585 Default `enable_cleanup_closed` to False
  changes/1585.bugfix.md
  hikari/impl/config.py
Labels: bug
