Repository hikari-py/hikari, pull requests merged in 2023-01, with the labels that each got.

#1435 Actually start bucket manager gc
  changes/1435.bugfix.md
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: bug, priority

#1434 Properly close unclosed file descriptor when reading banner
  changes/1434.bugfix.md
  hikari/internal/ux.py
  tests/hikari/internal/test_ux.py
Labels: bug

#1425 Suppress incorrect deprecation warning regarding event loops
  changes/1425.bugfix.md
  hikari/internal/aio.py
Labels: enhancement

#1426 Remove long deprecated `async with` support for `EventStream`
  changes/1426.breaking.md
  hikari/impl/event_manager_base.py
  tests/hikari/impl/test_event_manager_base.py
Labels: breaking

#1419 Improve error raised when attempting to use an asynchronous iterator synchronously.
  changes/idk.feature.md
  hikari/iterators.py
  tests/hikari/test_iterators.py
Labels: enhancement

#1416 Format code to be correct in the next black release
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/time.py
  tests/hikari/impl/test_entity_factory.py
Labels: skip-fragment-check

#1378 Deprecate delete_message_days for delete_message_seconds in ban methods
  changes/1378.deprecation.md
  changes/1378.feature.md
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/rest.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_guilds.py
Labels: enhancement

#1420 Add missing fields for `Application`
  changes/1420.feature.md
  hikari/applications.py
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#1421 Improve the docs TOC
  docs/_static/extra.css
  docs/conf.py
  hikari/impl/bot.py
  hikari/users.py
Labels: documentation, skip-fragment-check

#1431 Add a warning when not running in optimized mode
  changes/1431.feature.md
  hikari/impl/bot.py
  hikari/impl/rest_bot.py
  hikari/internal/ux.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_rest_bot.py
  tests/hikari/internal/test_ux.py
Labels: enhancement

#1134 Allow async iterators in delete_messages
  changes/1134.breaking.md
  changes/1134.feature.md
  hikari/errors.py
  hikari/impl/rest.py
  hikari/iterators.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_errors.py
Labels: enhancement

#1436 Fix incorrect value in `CommandBuilder.is_nsfw`.
  changes/1419.feature.md
  changes/1436.bugfix.md
  hikari/impl/special_endpoints.py
Labels: bug

#1430 Add support for guild forums
  changes/1430.feature.md
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/channels.py
  hikari/errors.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/ux.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_channels.py
  tests/hikari/test_errors.py
  tests/hikari/test_guilds.py
Labels: enhancement

#1230 Simplify and improve rest lifetime
  changes/1230.breaking.md
  changes/1230.bugfix.md
  changes/1230.feature.md
  examples/oauth.py
  hikari/impl/bot.py
  hikari/impl/buckets.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/net.py
  hikari/internal/routes.py
  tests/hikari/hikari_test_helpers.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_rest.py
  tests/hikari/internal/test_routes.py
Labels: enhancement, optimization

#1383 Support yielding in interaction handler
  changes/1383.feature.md
  hikari/api/interaction_server.py
  hikari/impl/interaction_server.py
  hikari/interactions/command_interactions.py
  tests/hikari/impl/test_interaction_server.py
Labels: enhancement

#1272 Add ability to save resources
  changes/1272.feature.md
  hikari/files.py
  tests/hikari/test_files.py
Labels: enhancement

#1438 Remove functionality scheduled for removal on 2.0.0.dev105
  changes/1438.breaking.md
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: breaking

#1439 Fix deserializing old forum channels on `GUILD_CREATE` missing some fields
  changes/1439.bugfix.md
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug

#1440 Add pull request number check to fragments check workflow
  .github/workflows/fragments-check.yml
  scripts/release-manually.sh
  scripts/release-webhook.sh
Labels: devops, skip-fragment-check

#1445 Bump features marked for deletion in 2.0.0.dev116 to 2.0.0.dev117
  hikari/guilds.py
  hikari/impl/rest.py
Labels: skip-fragment-check

#1442 Run CI tests on `bash` to exit fast on error on Windows
  .github/workflows/ci.yml
Labels: devops, skip-fragment-check

#1454 Create FUNDING.yml
  .github/FUNDING.yml
Labels: skip-fragment-check

#1459 Add ability to suppress optimization warnings
  changes/1459.feature.md
  hikari/impl/bot.py
  hikari/impl/rest_bot.py
  hikari/internal/ux.py
  tests/hikari/impl/test_bot.py
  tests/hikari/impl/test_rest_bot.py
  tests/hikari/internal/test_ux.py
Labels: enhancement

#1470 Remove description_localisations from context menu
  changes/1470.bugfix.md
  hikari/commands.py
  tests/hikari/test_commands.py
Labels: bug

#1469 Simplify twemoji pipeline
  dev-requirements/twemoji.txt
  pipelines/twemoji.nox.py
  scripts/test_twemoji_mapping.py
Labels: devops, skip-fragment-check

#1475 Implement `reply_must_exist` in create message methods
  changes/1475.feature.md
  hikari/api/rest.py
  hikari/channels.py
  hikari/impl/rest.py
  hikari/messages.py
  hikari/users.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_channels.py
  tests/hikari/test_messages.py
  tests/hikari/test_users.py
Labels: enhancement
