Repository hikari-py/hikari, pull requests merged in 2024-09, with the labels that each got.

#2044 Fix docstring typos pointing to incorrect events
  hikari/events/lifetime_events.py
Labels: documentation, skip-fragment-check

#2059 Fix uploading files when using aiohttp 3.10.6 and onwards
  .gitignore
  changes/2059.bugfix.md
  hikari/impl/interaction_server.py
Labels: bug

#2058 Add audit log reason to channel deletion
  changes/2058.feature.md
  hikari/api/rest.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: enhancement
