Repository hikari-py/hikari, pull requests merged in 2024-01, with the labels that each got.

#1570 Add deprecation utility decorator
  hikari/internal/deprecation.py
Labels: skip-fragment-check

#1812 `Member.joined_at` can now be None
  changes/1812.bugfix.md
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/internal/cache.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug

#1815 Ensure we have a loop when running ratelimit tests
  tests/hikari/impl/test_rate_limits.py
Labels: bug, testing, skip-fragment-check

#1813 Reset shard rate limiters per session
  changes/1813.bugfix.md
  hikari/impl/rate_limits.py
  hikari/impl/shard.py
Labels: bug

#1814 Allow subscribing to generic events
  changes/1814.feature.md
  hikari/impl/event_manager_base.py
  tests/hikari/impl/test_event_manager_base.py
Labels: enhancement
