Repository hikari-py/hikari, pull requests merged in 2025-03, with the labels that each got.

#1991 Add missing AuditLog event types
  changes/1991.feature.md
  hikari/audit_logs.py
Labels: enhancement

#2180 Only run CI on pushes to master or pull requests targetting master
  .github/workflows/ci.yml
Labels: devops, skip-fragment-check

#2194 Lock jinja2 to >=3.1.6
  uv.lock
Labels: skip-fragment-check

#2195 User applications removals
  changes/2195.breaking.md
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/commands.py
  hikari/impl/cache.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/cache.py
  hikari/messages.py
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/test_commands.py
  tests/hikari/test_messages.py
Labels: breaking

#2197 Fix application command deserialization when context is None
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug, skip-fragment-check

#2198 Do not run pytest with coverage by default
  .github/workflows/ci.yml
  pipelines/pytest.nox.py
Labels: devops, skip-fragment-check

#2202 Update twemoji mapping url
  scripts/ci/test_twemoji_mapping.py
Labels: devops, skip-fragment-check

#2210 General housekeeping
  .github/CODEOWNERS
  .github/FUNDING.yml
  README.md
  SECURITY.md
Labels: skip-fragment-check

#2217 Pin CI actions
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fragments-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
Labels: devops, skip-fragment-check

#2224 Remove redundant `with_expiration` parameter from `fetch_invite` methods
  changes/2224.breaking.md
  hikari/api/rest.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: a lost feature, breaking

#2228 Use uv as package manager in the contribution guide
  CONTRIBUTING.md
  README.md
Labels: documentation, skip-fragment-check

#2242 Remove outdated rillrate example
  examples/simple_dashboard.py
  examples/simple_dashboard_requirements.txt
Labels: documentation, skip-fragment-check

#1621 Add new interaction channel attribute
  changes/1621.breaking.md
  changes/1621.feature.md
  hikari/api/entity_factory.py
  hikari/channels.py
  hikari/impl/entity_factory.py
  hikari/interactions/base_interactions.py
  hikari/interactions/command_interactions.py
  hikari/interactions/component_interactions.py
  hikari/interactions/modal_interactions.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_interaction_server.py
  tests/hikari/interactions/test_base_interactions.py
  tests/hikari/interactions/test_command_interactions.py
  tests/hikari/interactions/test_component_interactions.py
  tests/hikari/interactions/test_modal_interactions.py
Labels: enhancement

#2246 Fix prepare release workflow
  .github/workflows/prepare-release.yml
Labels: devops, skip-fragment-check

#2247 Fix prerelease flow (take 2)
  .github/workflows/prepare-release.yml
Labels: devops, skip-fragment-check

#2248 Use correct token for pre release workflow
  .github/workflows/prepare-release.yml
Labels: devops, skip-fragment-check

#2250 Properly mention release author
  .github/workflows/prepare-release.yml
Labels: devops, skip-fragment-check

#2252 Speedup protocol checking
  CONTRIBUTING.md
  changes/2252.optimization.md
  hikari/internal/fast_protocol.py
  pyproject.toml
  scripts/benchmarks/protocol_benchmark.py
  tests/hikari/internal/test_fast_protocols.py
Labels: optimization

#2254 Switch from codeclimate to codecov
  .codeclimate.yml
  .github/workflows/ci.yml
  README.md
  codecov.yml
  hikari/_about.py
Labels: devops, skip-fragment-check

#2255 Fix TOC jumping around when scrolling by disabling toc.follow
  changes/2255.documentation.md
  hikari/intents.py
  mkdocs.yml
Labels: documentation

#2262 Fix docs of create_role
  hikari/api/rest.py
Labels: documentation, skip-fragment-check

#2219 Add polls support
  changes/2219.feature.md
  hikari/__init__.py
  hikari/__init__.pyi
  hikari/api/entity_factory.py
  hikari/api/event_factory.py
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/events/poll_events.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/intents.py
  hikari/internal/cache.py
  hikari/internal/routes.py
  hikari/messages.py
  hikari/polls.py
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/test_messages.py
Labels: enhancement

#2265 feat: support for poll parameter in utility methods
  hikari/interactions/base_interactions.py
  hikari/messages.py
  hikari/webhooks.py
  tests/hikari/interactions/test_base_interactions.py
  tests/hikari/test_webhooks.py
Labels: skip-fragment-check

#2266 feat: poll support for REST-based interaction responses
  hikari/api/special_endpoints.py
  hikari/impl/special_endpoints.py
Labels: skip-fragment-check

#2268 Remove flake8 dependency group
  pyproject.toml
Labels: devops, skip-fragment-check

#2272 Remove disused `poll` argument from `message.edit`.
  hikari/messages.py
  tests/hikari/test_messages.py
Labels: skip-fragment-check

#2244 Enforce `@typing.override` and missing abstract methods
  changes/2244.bugfix.md
  hikari/api/event_manager.py
  hikari/api/special_endpoints.py
  hikari/applications.py
  hikari/audit_logs.py
  hikari/channels.py
  hikari/colors.py
  hikari/embeds.py
  hikari/emojis.py
  hikari/errors.py
  hikari/events/base_events.py
  hikari/events/channel_events.py
  hikari/events/guild_events.py
  hikari/events/interaction_events.py
  hikari/events/member_events.py
  hikari/events/message_events.py
  hikari/events/reaction_events.py
  hikari/events/role_events.py
  hikari/events/scheduled_events.py
  hikari/events/shard_events.py
  hikari/events/stage_events.py
  hikari/events/typing_events.py
  hikari/events/user_events.py
  hikari/events/voice_events.py
  hikari/files.py
  hikari/guilds.py
  hikari/impl/buckets.py
  hikari/impl/cache.py
  hikari/impl/config.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager_base.py
  hikari/impl/gateway_bot.py
  hikari/impl/interaction_server.py
  hikari/impl/rate_limits.py
  hikari/impl/rest.py
  hikari/impl/rest_bot.py
  hikari/impl/shard.py
  hikari/impl/special_endpoints.py
  hikari/impl/voice.py
  hikari/interactions/base_interactions.py
  hikari/internal/cache.py
  hikari/internal/collections.py
  hikari/internal/enums.py
  hikari/internal/enums.pyi
  hikari/internal/routes.py
  hikari/internal/ux.py
  hikari/invites.py
  hikari/iterators.py
  hikari/messages.py
  hikari/presences.py
  hikari/snowflakes.py
  hikari/templates.py
  hikari/undefined.py
  hikari/users.py
  hikari/voices.py
  hikari/webhooks.py
  pyproject.toml
  ruff.toml
Labels: enhancement, devops

#2276 Disable renovate semantic commits
  .github/renovate.json
Labels: devops, skip-fragment-check
