Repository hikari-py/hikari, pull requests merged in 2025-06, with the labels that each got.

#2415 Bump requests to 2.32.4 to mitigate CVE
  uv.lock
Labels: skip-fragment-check

#2399 Implement Message Forwarding
  changes/2399.feature.md
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/cache.py
  hikari/messages.py
  tests/hikari/impl/test_cache.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_messages.py
Labels: enhancement

#2425 Revert "Only lock buckets to a single request if they are unknown"
  changes/2403.optimization.md
  hikari/impl/buckets.py
  tests/hikari/impl/test_buckets.py
Labels: skip-fragment-check

#2428 Bump urllib3 lock to fix CVE-2025-50181
  uv.lock
Labels: skip-fragment-check

#2427 Switch ratelimiting logic to a sliding window
  changes/2427.optimization.md
  hikari/impl/buckets.py
  hikari/impl/event_manager.py
  hikari/impl/gateway_bot.py
  hikari/impl/rate_limits.py
  hikari/impl/rest.py
  hikari/impl/shard.py
  hikari/internal/routes.py
  hikari/internal/time.py
  tests/hikari/impl/test_buckets.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_interaction_server.py
  tests/hikari/impl/test_rate_limits.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_shard.py
Labels: enhancement, optimization

#2434 Fix enum `__getitem__` not properly returning items with a falsy value
  changes/2434.bugfix.md
  hikari/internal/enums.py
Labels: bug

#2436 Bump multidict to avoid yanked version
  uv.lock
Labels: skip-fragment-check

#2435 Fix deserializing message snapshots
  changes/2435.bugfix.md
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: bug
