Repository hikari-py/hikari, pull requests merged in 2025-02, with the labels that each got.

#2169 Fix failing macOS test due to closed event loop
  tests/hikari/internal/test_aio.py
Labels: testing, skip-fragment-check

#2105 Allow setting `name` and `value` of an `EmbedField` to an empty string
  changes/2105.feature.md
  hikari/embeds.py
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/test_embeds.py
Labels: enhancement

#2168 Properly handle cloudflare bans
  changes/2168.bugfix.md
  hikari/impl/rest.py
Labels: bug
