Repository hikari-py/hikari, pull requests merged in 2025-05, with the labels that each got.

#2338 Add AWEBP support, increase sticker asset availability and deprecate `x_url` properties
  changes/2338.deprecation.md
  changes/2338.feature.md
  hikari/applications.py
  hikari/channels.py
  hikari/guilds.py
  hikari/internal/deprecation.py
  hikari/internal/routes.py
  hikari/internal/typing_extensions.py
  hikari/invites.py
  hikari/messages.py
  hikari/presences.py
  hikari/scheduled_events.py
  hikari/stickers.py
  hikari/users.py
  hikari/webhooks.py
  tests/hikari/internal/test_routes.py
  tests/hikari/test_applications.py
  tests/hikari/test_channels.py
  tests/hikari/test_guilds.py
  tests/hikari/test_invites.py
  tests/hikari/test_messages.py
  tests/hikari/test_presences.py
  tests/hikari/test_scheduled_events.py
  tests/hikari/test_stickers.py
  tests/hikari/test_users.py
  tests/hikari/test_webhooks.py
Labels: enhancement

#2353 Add `old_thread` field to `GuildThreadUpdateEvent`
  changes/2353.feature.md
  hikari/api/event_factory.py
  hikari/events/channel_events.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  tests/hikari/events/test_channel_events.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/test_invites.py
  tests/hikari/test_webhooks.py
Labels: enhancement

#2355 Add missing voice message docstrings
  changes/2355.bugfix.md
  hikari/api/rest.py
Labels: documentation

#2354 Add reason argument to missing routes
  changes/2354.feature.md
  hikari/api/rest.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: enhancement

#2370 Ignore typing overloads when counting coverage
  pyproject.toml
Labels: devops, skip-fragment-check

#2369 Add `startup_window_delay`
  changes/2369.feature.md
  hikari/impl/gateway_bot.py
  tests/hikari/impl/test_gateway_bot.py
Labels: enhancement

#2368 Greatly optimize event manager memory management
  changes/2368.optimization.md
  hikari/api/event_manager.py
  hikari/impl/event_manager.py
  hikari/impl/event_manager_base.py
  hikari/impl/gateway_bot.py
  hikari/impl/shard.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_gateway_bot.py
Labels: optimization

#2365 Do not try to stringify http message assuming it will be ascii
  changes/2365.bugfix.md
  hikari/impl/rest.py
Labels: bug

#2380 Dedupe channels`__all__`
  hikari/channels.py
Labels: skip-fragment-check

#2387 Fixup changelog fragment for 2383
  changes/2383.documentation.md
Labels: documentation, skip-fragment-check

#2381 docs: enable show_if_no_docstring
  changes/2381.documentation.md
  mkdocs.yml
Labels: enhancement

#2382 fix(MessageType): add some missing message types.
  changes/2382.feature.md
  hikari/messages.py
Labels: enhancement

#2389 Improve readme
  README.md
Labels: documentation, skip-fragment-check

#2394 Name event dispatch tasks
  changes/2394.feature.md
  changes/2394.optimization.md
  hikari/impl/event_manager_base.py
Labels: enhancement, optimization

#2395 Allow setting HTTP concurrent connection limit
  changes/2395.feature.md
  hikari/impl/config.py
  hikari/impl/shard.py
  hikari/internal/net.py
  hikari/internal/ux.py
  tests/hikari/impl/test_shard.py
  tests/hikari/internal/test_ux.py
Labels: enhancement

#2396 Default connection limit to 'no limit'
  hikari/impl/config.py
Labels: skip-fragment-check

#2397 Bump aiohttp version to ~=3.12
  hikari/impl/shard.py
  pyproject.toml
  uv.lock
Labels: skip-fragment-check
