Repository hikari-py/hikari, pull requests merged in 2025-04, with the labels that each got.

#2282 Update lockfile
  uv.lock
Labels: skip-fragment-check

#2287 Fix `end_poll` method in `RESTClient`.
  hikari/api/rest.py
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: enhancement, skip-fragment-check

#2289 Implement guild incidents/incident actions.
  changes/2289.feature.md
  hikari/api/entity_factory.py
  hikari/api/rest.py
  hikari/guilds.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/internal/routes.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/test_guilds.py
Labels: enhancement

#2293 Fix `set_guild_incident_actions` documentation typo
  hikari/api/rest.py
  hikari/guilds.py
Labels: documentation, skip-fragment-check

#2298 Use `--locked` instead of `--frozen` when syncing nox pipelines
  pipelines/nox.py
Labels: devops, skip-fragment-check

#2299 docs: add unit for poll builder duration
  hikari/api/special_endpoints.py
Labels: documentation, skip-fragment-check

#2303 Add approximate_user_install_count attribute to hikari.Application
  changes/2303.bugfix.md
  hikari/applications.py
  hikari/impl/entity_factory.py
  tests/hikari/impl/test_entity_factory.py
Labels: enhancement

#2304 Downgrade multidict to non yanked version
  uv.lock
Labels: devops, skip-fragment-check

#2314 Update UserFlags with more values and improved descriptions.
  changes/2314.feature.md
  hikari/users.py
Labels: enhancement

#2317 Run slotscheck with verbose output
  pipelines/slotscheck.nox.py
Labels: devops, skip-fragment-check

#2196 Components V2!
  changes/2196.feature.md
  hikari/api/special_endpoints.py
  hikari/components.py
  hikari/impl/entity_factory.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/internal/cache.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/interactions/test_modal_interactions.py
  tests/hikari/test_components.py
Labels: enhancement

#2320 Update aiohttp pin to 3.11.18
  uv.lock
Labels: skip-fragment-check

#2318 Add missing tests for components V2
  tests/hikari/impl/test_rest.py
Labels: testing, skip-fragment-check

#2321 Add components v2 Discord documentation link
  changes/2196.feature.md
Labels: documentation, skip-fragment-check

#2328 Bump httpcore lock to 1.0.9
  uv.lock
Labels: devops, skip-fragment-check

#2329 Set button builder specifics in the sub-builders
  hikari/impl/special_endpoints.py
  tests/hikari/impl/test_special_endpoints.py
Labels: enhancement, skip-fragment-check

#2330 Fix sending modal builders
  changes/2330.bugfix.md
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: bug

#2205 Implement auto-moderation
  changes/2205.feature.md
  hikari/__init__.py
  hikari/__init__.pyi
  hikari/api/entity_factory.py
  hikari/api/event_factory.py
  hikari/api/rest.py
  hikari/api/special_endpoints.py
  hikari/audit_logs.py
  hikari/auto_mod.py
  hikari/events/__init__.py
  hikari/events/__init__.pyi
  hikari/events/auto_mod_events.py
  hikari/impl/entity_factory.py
  hikari/impl/event_factory.py
  hikari/impl/event_manager.py
  hikari/impl/rest.py
  hikari/impl/special_endpoints.py
  hikari/intents.py
  hikari/internal/routes.py
  hikari/messages.py
  tests/hikari/impl/test_entity_factory.py
  tests/hikari/impl/test_event_factory.py
  tests/hikari/impl/test_event_manager.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
  tests/hikari/test_audit_logs.py
Labels: enhancement

#2335 Fix event filtering for interaction create specialized events
  changes/2335.bugfix.md
  hikari/impl/event_manager.py
Labels: bug

#2336 Fix duplicated uploaded attachments when reusing resources in embeds
  changes/2336.bugfix.md
  changes/2336.optimization.md
  hikari/impl/rest.py
  tests/hikari/impl/test_rest.py
Labels: bug, enhancement, optimization

#2339 Remove leftover mentions of flake8
  CONTRIBUTING.md
  tests/hikari/impl/test_event_manager_base.py
  tests/hikari/impl/test_rest.py
  tests/hikari/impl/test_special_endpoints.py
Labels: documentation, skip-fragment-check
